---
title: "Preparation_organoids"
output: html_notebook
---


### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```


```{r}
library(ggpubr)
library(xlsx)
library(ggrepel)
library(limma)
```


```{r}
col <- c("#878782", "#761212")
```

```{r}
brain <- read.csv("/home/flomik/Desktop/Code-PHD/COCOMO_txn/manuscript/brain_genes_ujjwal.csv")
```


### clinical paraolinkers
```{r}
clinical <- read.csv("processing/clinical_data_clean_with_clusters_and_categories.csv")
```

### olink
```{r}
data <- read.csv("processing/olink_data_new_ids.csv", row.names = 1)
data$Condition <- NULL
```

# Metabolomics
```{r}
data_met <- read.csv("processing/COCOMO_metabolomics_log2_norm_filt.csv", row.names = 1, check.names = FALSE)
data_met <- data.frame(t(data_met))
metabolites <- rownames(data_met)
data_met <- data.frame(t(data_met))

rownames(data_met) <- gsub("X", "", rownames(data_met))
colnames(data_met) <- metabolites
data_met$COCOMO_ID <- rownames(data_met)
pca_data <- merge(clinical, data_met, by = "COCOMO_ID")
rownames(pca_data) <- pca_data$COCOMO_ID
pca_data <- pca_data[pca_data$COCOMO_ID %in% rownames(data),]
```

```{r}
list_met <- c("glutamate","glutamine", "alpha-ketoglutarate", "carboxyethyl-GABA", "spermidine", "5alpha-androstan-3alpha,17beta-diol monosulfate (1)",
"androsterone sulfate",
"epiandrosterone sulfate",
"metabolonic lactone sulfate")
```

```{r}
pca_data <- pca_data[, colnames(pca_data) %in% c("cluster", list_met)]
pca_data$cluster <- ifelse(pca_data$cluster == 1, "HC-like", "At-risk")
pca_data$cluster <- factor(pca_data$cluster, levels = c("HC-like", "At-risk"))
```

```{r}
my_comparisons <- list(c("HC-like", "At-risk"))
```

```{r}
data_SASP <- pca_data
list_x <- list()
x = 1

for (i in 2:ncol(data_SASP)) {
  table_1 <- data_SASP[,c(i, 1)]
  a <- ggplot(table_1, aes(x = cluster, y = table_1[,1], fill = cluster)) + 
    geom_boxplot(position=position_dodge(1), size = 0.1, alpha =0.8, outlier.shape = NA)+ 
    labs(x="Cluster", y = paste0(names(table_1)[1], ""))+ 
    theme(axis.title.x = element_blank(),
          axis.title.y = element_text(size=16, face = "bold",color="black"),
          axis.text = element_text(color="black",size=16, face = "bold"),
          axis.text.x =element_text(color="black",size=16, face = "bold"),
          panel.border = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text.x = element_text(size = 9,color="black"),
          legend.position="none",
          panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
          panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
          panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
          plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
          legend.background=element_rect(fill = alpha("white", 0))) + 
    geom_jitter(shape=16, size=1, color="black", position=position_jitter(0.05))+ scale_fill_manual(values=col)+ 
  stat_compare_means(comparisons = my_comparisons)
  a
  ggsave(paste0("results/figures/boxplots/Met_boxplot_", colnames(data_SASP)[i], ".pdf"), height = 4, width = 3.5)
  print(i)
  list_x[[x]] <- a
  x <- x + 1
}
```
```{r}
pca_data$COCOMO_ID <- rownames(pca_data)
pca_data <- pca_data[order(pca_data$spermidine),]
```

```{r}
x <- pca_data[pca_data$cluster == "HC-like", colnames(pca_data) %in% c("COCOMO_ID", "spermidine")]
x2 <- x[1:10,]
x2$cluster <- "HC-like"
y <- pca_data[pca_data$cluster == "At-risk", colnames(pca_data) %in% c("COCOMO_ID", "spermidine")]
y2 <- y[61:70,]
y2$cluster <- "At-risk"

patients <- rbind(x2, y2)
write.csv(patients,"manuscript/COCOMO_patients_10_HC-like_10_At-risk_spermidine.csv")
```

# OLINK

## Neurology
```{r}
neuro <- read.xlsx("/home/flomik/Desktop/Code-PHD/COCOMO_txn/data/Olink/Neurology.xlsx", 1)
neuro <- neuro[!is.na(neuro$Explore.384.panel),]
write.csv(neuro, "processing/olink_neurological_panel.csv")
```

### Volcano plot
```{r}
dge <- read.csv("results/LIMMA/model_3_LIMMA_results_olink_with_HC.csv", sep = ",")
dge <- dge[dge$BIOCHEMICAL %in% neuro$Protein,]
write.csv(dge, "processing/olink_neurological_panel_dge.csv")

tt <- dge
tt$X <- NULL
name_ana <- unique(tt$Comp)
tt$color <- NA

for (i in 1:nrow(tt)){
  if(tt[i, 2] > 1.5 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "up_regulated_>1.5"
  }
  if(tt[i, 2] > 1 & tt[i, 2] < 1.5 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "up_regulated_1>x>1.5"
  }
  if(tt[i, 2] > 0 & tt[i, 2] < 1 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "up_regulated_0>x>1"
  }
  if(tt[i, 2] < 0 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "down_regulated"
  }
  if(tt[i, 4] > 0.05){
    tt[i, ncol(tt)] <- "NS"
    #tt[i, 1] <- NA
  }
}

tt$BIOCHEMICAL <- ifelse(abs(tt$logFC) > 2 & tt$adj.P.Val < 0.000001, as.vector(tt$BIOCHEMICAL), NA)
length(tt$BIOCHEMICAL[!is.na(tt$BIOCHEMICAL)])


tt$color[is.na(tt$color)] <- "significant"
#tt$Gene_name[tt$color == "significant"] <- NA
cols <- c("up_regulated_>1.5" = "#cb4818",
          "up_regulated_1>x>1.5" = "#d27f28", 
          "up_regulated_0>x>1" = "#f1c232", 
          "down_regulated" = "#86b7e8", 
          "NS" = "grey", 
          "significant" = "#586c6e")

vol <- ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val), colour = color, size = abs(logFC)))+ 
  geom_point(alpha = 1, na.rm = T)+ 
  theme(legend.title=element_text(size=2),legend.text=element_text(size=2),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=25),axis.title.x=element_text(size=25),
        axis.text.y=element_text(size=25),axis.text.x=element_text(size=25)) +
  labs(x="Log2 Fold Change",y="-log10 (adj.P.Val)")+
  geom_text_repel(aes(label = BIOCHEMICAL),size=2,label.size = 0.1, color = "black", xlim = c(NA, Inf),
    # Do not repel from top or bottom edges.
    ylim = c(-Inf, Inf))+ theme_classic()+ 
  geom_hline(yintercept=-log10(0.05), linetype="dashed", color = "black")+scale_color_manual(values = cols)

print(vol)
path_fig <- paste0("results/figures/volcano_plots/", name_ana, "_volcano_plot_neuro_panel_olink.pdf")
ggsave(path_fig, width = 10, height = 6)
```

### DGE
```{r}
dge <- read.csv("results/LIMMA/model_3_LIMMA_results_olink_with_HC_filt.csv", sep = " ")
dge <- dge[dge$adj.P.Val < 0.05, ]
dge <- dge[dge$BIOCHEMICAL %in% neuro$Protein,]
```

### olink
```{r}
data <- read.csv("processing/olink_data_new_ids.csv", row.names = 1)
data$Condition <- NULL
```

```{r}
clinical <- read.csv("processing/clinical_data_clean_paper_4.csv", row.names = 2)
clinical$X.1 <- NULL
clinical$COCOMO_ID <- rownames(clinical)
```

```{r}
data$COCOMO_ID <- rownames(data)
pca_data <- merge(clinical, data, by = "COCOMO_ID")
```


```{r}
#pca_data <- pca_data[!is.na(pca_data$H2_56),]
pca_data <- pca_data[!is.na(pca_data$status_smoking),]
pca_data$status_smoking <- as.vector(pca_data$status_smoking)
pca_data$status_smoking[pca_data$status_smoking == "Current smoker"] <- 2
pca_data$status_smoking[pca_data$status_smoking == "Ex smoker"] <- 1
pca_data$status_smoking[pca_data$status_smoking == "Never smoker"] <- 0
```


```{r}
table(patients$cluster)
```
```{r}
patients$COCOMO_ID[!patients$COCOMO_ID %in% pca_data$COCOMO_ID]
```

```{r}
pca_data_2 <- pca_data[pca_data$COCOMO_ID %in% patients$COCOMO_ID,]

group <- as.factor(pca_data_2$cluster)
fish <- pca_data_2$H2_52c
meat <- pca_data_2$H2_53a
fruit <- as.factor(pca_data_2$H2_56)
ethn <- pca_data_2$Ethnic
ethn[is.na(ethn)] <- 0
ethn <- as.factor(ethn)
smok <- as.factor(pca_data_2$status_smoking)

design <- model.matrix( ~ 0 + group + smok + ethn)
```

```{r}
fit <- lmFit(t(pca_data_2[,-c(1:165)]), design)
```

```{r}
list_comp <- c(paste0("group",2:1))
list_pair <- data.frame(t(combn(list_comp,2)))
list_pair$comp <- paste0(list_pair$X1, "-", list_pair$X2)
comp <- list_pair$comp
names(comp) <- gsub("roup", "", comp)
```

```{r}
cont.matrix <- makeContrasts(G2_G1 = comp[1],
                             levels=design)

fit.cont <- contrasts.fit(fit, cont.matrix)
fit.cont <- eBayes(fit.cont)
```

```{r}
top_table <- data.frame(BIOCHEMICAL = NA, logFC= NA, P.Value= NA, adj.P.Val= NA, Comp= NA)

top_table_1 <- topTable(fit.cont, adjust="BH", n = Inf, sort.by = "P")
top_table_1$Comp <- comp[1]
top_table_1$BIOCHEMICAL <- rownames(top_table_1)
top_table_1 <- top_table_1[,c(8, 1, 4, 5, 7)]
write.table(top_table_1$BIOCHEMICAL[top_table_1$adj.P.Val < 0.05], paste0("processing/MSEA/model_3_olink_10_patients_", comp[i],".txt"), quote = FALSE, row.names = F)
top_table <- rbind(top_table, top_table_1)

top_table <- top_table[complete.cases(top_table),]
path_table <- paste0("results/LIMMA/model_3_LIMMA_results_olink10_patients.csv")

print(path_table)
write.csv(top_table, file =path_table)

DF_top_table <-top_table[top_table$adj.P.Val < 0.05, ]

path_results <- paste0("results/LIMMA/model_3_LIMMA_results_olink_10_patients_filt.csv")

write.table(DF_top_table, file = path_results)

path_results <- paste0("results/LIMMA/model_3_LIMMA_results_olink_10_patients_filt.xlsx")

write.xlsx(DF_top_table, file = path_results)

table(DF_top_table$Comp)
```

```{r}
pca_data$cluster <- ifelse(pca_data$cluster == 1, "HC-like", "At-risk")
pca_data$cluster <- as.factor(pca_data$cluster)
rownames(pca_data) <- pca_data$COCOMO_ID
pca_data <- pca_data[,colnames(pca_data) %in% c("cluster", as.vector(dge$BIOCHEMICAL))]
```

## heatmap patients

```{r}
library(circlize)
library(viridis)
col_fun1 = colorRamp2(c(-5,-2.5, -0.75, 0, 0.75, 2.5, 5), c("#7F7F00","#B2B200" ,"#E5E500","white","#BF7FBF","#993299","#590059"))
col_fun_2 = colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))
```

```{r}
cluster <- pca_data$cluster
pca_data <- pca_data[,colnames(pca_data) %in% c("cluster", as.vector(dge$BIOCHEMICAL))]
data_prot <- pca_data[,-c(1:165)]
data_prot <- data.frame(t(data_prot))
```

```{r}
data_prot$BIOCHEMICAL <- rownames(data_prot)
```

```{r}
data_prot <- merge(dge, data_prot, by = "BIOCHEMICAL")
```
```{r}
library(ComplexHeatmap)
```
```{r}
col
```
```{r}
data_prot[,-c(1:5)] <- data.frame(t(scale(t(data_prot[,-c(1:5)]))))
```

```{r}
data_prot[data_prot < -5] <- -5
```

```{r}
data_prot$Synaptic <- ifelse(data_prot$BIOCHEMICAL %in% brain$HumanName, "yes", NA)
```

```{r}
name_prot <- data_prot$BIOCHEMICAL
name_prot[!name_prot %in% brain$HumanName] <- ""
```


```{r}
pdf("results/figures/Heatmap_neuro_olink.pdf", width = 7, height = 6)
ht = Heatmap(data_prot[,-c(1:5, 164)], 
             #column_order = sort(colnames(t(data_prot_6[,-c(1:5)]))),  
             col = col_fun1, 
             show_column_names = FALSE, 
             show_row_names = TRUE,
             #column_split = cluster, 
             #row_split = data_2$under_group, 
             #column_title = c("Ctrl",1, 2), 
             #column_title_gp = gpar(fill = col), 
             border = FALSE, 
             column_gap = unit(2, "mm"), 
             row_labels = name_prot,
             right_annotation = rowAnnotation(LogFC = data_prot$logFC, Synaptic = data_prot$Synaptic,
                                              col = list(LogFC = col_fun_2, Synaptic = c("yes" = "#8b74d4")), show_legend = TRUE),
             top_annotation = HeatmapAnnotation(cluster = cluster,
                                              col = list(cluster = c("HC-like" = col[1], "At-risk" = col[2])), show_legend = TRUE),
             name = "Z-score"
             )
draw(ht)
dev.off()

ht
```

## PCA genes
```{r}
pca <- prcomp(pca_data[,-c(1)])
df_out <- as.data.frame(pca$x)
df_out$group <- as.factor(pca_data$cluster)
rownames(df_out) <- rownames(pca_data)
x <- project.pca.proportionvariances <- ((pca$sdev^2) / (sum(pca$sdev^2)))*100
a1 <- x[1]
a2 <- x[2]

gg <- data.frame(cluster=factor(df_out$group), x=df_out$PC1, y=df_out$PC2)
rownames(gg) <- rownames(df_out)
centroids <- aggregate(cbind(x,y)~cluster,data=gg,mean)
gg <- merge(gg,centroids,by="cluster",suffixes=c("",".centroid"))
rownames(gg) <- rownames(df_out)
gg$label <- rownames(gg)
```


```{r}
col <- c("#761212", "#878782")
```

```{r}
gg$label[gg$x < -70 | gg$y < -30]
```

```{r}
gg <- gg[gg$x > -70 & gg$y > -30,]
```

```{r}
ggplot(gg)+
      geom_point(aes(x=x,y=y,color=cluster, fill = cluster), size=3)+
      stat_ellipse(geom = "polygon", aes(x=x,y=y,color=cluster, fill = cluster), alpha = 0.3) +
      geom_point(data=centroids, aes(x=x, y=y, color=cluster, fill = cluster), size = 5, alpha = 0.9, shape = 19)+ 
      geom_segment(aes(x=x.centroid, y=y.centroid, xend=x, yend=y, color=cluster))+
      theme(legend.title=element_text(size=15),legend.text=element_text(size=12),
            legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
            axis.title.y=element_text(size=15),axis.title.x=element_text(size=15),
            axis.text.y=element_text(size=18),axis.text.x=element_text(size=18))+
      xlab(paste0("PC1: ",round(a1,0),"% variance"))+
      ylab(paste0("PC2: ",round(a2,0),"% variance"))+ 
        theme(axis.title.x = element_text(size=16, face = "bold",color="black"),
              axis.title.y = element_text(size=16, face = "bold",color="black"),
              axis.text = element_text(color="black",size=16, face = "bold"),
              axis.text.x =element_text(color="black",size=16, face = "bold"),
              panel.border = element_blank(),
              axis.ticks.x = element_blank(),
              strip.text.x = element_text(size = 9,color="black"),
              panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
              panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
              panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
              plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
              legend.background=element_rect(fill = alpha("white", 0)))+ scale_color_manual(values = col)+ scale_fill_manual(values = col)

path_fig <- paste0("results/figures/PCA/PCA_top_patients_olink_10_10_centroids.pdf")
ggsave(path_fig, width = 7, height = 6)
```
