---
title: "R Notebook"
output: html_notebook
---


### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```

```{r}
library(piano)
library(ggplot2)
library(dplyr)
library(reshape2)
```

```{r}
name_ana <- "GSEA_proteomics_organoids_KEGG"
```

```{r}
gset=loadGSC("/home/flomik/Desktop/Code-PHD/COCOMO_txn/data/GSEA/c2.cp.kegg.v7.5.1.symbols.gmt")
```



```{r}
table_global <- data.frame(Name = NA, Stat..dist.dir.up.= NA, p.adj..dist.dir.up.= NA, Genes..up. = NA, Stat..dist.dir.dn.= NA, p.adj..dist.dir.dn.= NA, Genes..down. = NA, comp = NA, sign = NA)


x <- list.files("/home/flomik/Desktop/Code-PHD/COCOMO_txn/processing/GSEA")
input <- x[!grepl("extra", x) & !grepl("KEGG_", x) & grepl("organoid", x) & grepl("_frac", x) & grepl("_log", x)]


for (i in input) {
  tryCatch({
    name <- gsub(".csv", "", i)
    DESeqout <- read.csv(paste0("/home/flomik/Desktop/Code-PHD/COCOMO_txn/processing/GSEA/", i))
    DESeqout <- DESeqout[order(DESeqout$P.Value),]
    DESeqout <- DESeqout[!is.na(DESeqout$Gene_name),]
    DESeqout <- DESeqout[!duplicated(DESeqout$Gene_name),]
    rownames(DESeqout) <- DESeqout$Gene_name
    DESeqout$Gene_name <- NULL
    pval= as.matrix(DESeqout[ ,2]) 
    fc= as.matrix(DESeqout[ ,1]) 

    row.names(pval)=row.names(DESeqout)
    row.names(fc)=row.names(DESeqout)
  
    #Main function in PIANO. Uses the pvalues, fold-changes, and gene sets. 
    gsaRes <- runGSA(pval,fc,gsc=gset, nPerm = 1000, adjMethod = "fdr", gsSizeLim=c(10,800))

    #Writes the output from PIANO to a file "piano.txt". Setting "save=FALSE" simply shows the result from PIANO
    GSAsummaryTable(gsaRes, save=TRUE, file=paste0("processing/GSEA/KEGG_", name_ana, "_",name[i], "_2.txt"))
    c <- read.delim(paste0("/home/flomik/Desktop/Code-PHD/COCOMO_txn/processing/GSEA/KEGG_", name_ana, "_", name[i], "_2.txt"))
    c <- c[,c(1, 3, 5, 12, 6, 8, 16)]
    c_up <- c[c$p.adj..dist.dir.up. < 0.2, ]
    c_down <- c[c$p.adj..dist.dir.dn. < 0.2, ]
    print(nrow(c_up))
    print(nrow(c_down))
    
    table_piano <- data.frame(Name = NA, Stat..dist.dir.up.= NA, p.adj..dist.dir.up.= NA, Genes..up. = NA, Stat..dist.dir.dn.= NA, p.adj..dist.dir.dn.= NA, Genes..down. = NA, comp = NA, sign = NA)
    if (nrow(c_up) > 1) {
      c_up$comp <- name
      c_up$sign <- "up"
      table_piano <- rbind(c_up, table_piano)
    }
    if (nrow(c_down) > 1) {
      c_down$comp <- name
      c_down$sign <- "down"
      table_piano <- rbind(c_down, table_piano)
    }
    
    table_global <- rbind(table_global, table_piano)
    
  }, error=function(e){cat("ERROR :",i, "\n")})
}
```


```{r}
table_global_2 <- table_global[!is.na(table_global$Name),]
table(table_global_2$comp)
write.csv(table_global_2, paste0("processing/GSEA/hallmark_", name_ana, "_all_comparisons.csv"))
```

```{r}
gsea <- read.csv("/home/flomik/Desktop/Code-PHD/COCOMO_txn/processing/GSEA/hallmark_GSEA_proteomics_organoids_KEGG_all_comparisons.csv")
table_global_2 <- gsea[gsea$comp == "proteomics_organoids_SPD_controls_frac_log2",]

table_global_2$comp <- gsub("proteomics_organoids_", "", table_global_2$comp)
table_global_2$comp <- gsub("_frac_log2", "", table_global_2$comp)
table_global_2$pvalue <- ifelse(table_global_2$sign == "up", table_global_2$p.adj..dist.dir.up., table_global_2$p.adj..dist.dir.dn.)
table_global_2$Nb <- ifelse(table_global_2$sign == "up", table_global_2$Genes..up., table_global_2$Genes..down.)
table_global_2$Stat <- ifelse(table_global_2$sign == "up", table_global_2$Stat..dist.dir.up., table_global_2$Stat..dist.dir.dn.)

table_global_2$Stat <- ifelse(table_global_2$sign == "up", table_global_2$Stat, -table_global_2$Stat)

table_global_2$Name <- gsub("KEGG_", "", table_global_2$Name)

table_global_2 <- table_global_2[!grepl("DISEASE", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("CANCER", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("CARDIOMYOPATHY", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("INFECTION", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("CARDIOMYOPATHY", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("CARDIOMYOPATHY", table_global_2$Name),]

table_global_2 <- table_global_2[!table_global_2$Name %in% c("PORPHYRIN_AND_CHLOROPHYLL_METABOLISM", "OLFACTORY_TRANSDUCTION", "MELANOGENESIS"),]


write.csv(table_global_2, paste0("processing/GSEA/GSEA_", name_ana, "_Control_vs_SPD.csv"))

#table_global_2 <- table_global_2[table_global_2$pvalue < 0.02,]
```

/home/flomik/Desktop/Code-PHD/COCOMO_txn/manuscript/SPD_pathway.xlsx
## figure qui casse les couilles
```{r}
table_global_2 <- table_global_2[,c(2, 10:13)]
table_global_2$label <- tolower(table_global_2$Name)
table_global_2$label[!table_global_2$Name %in% c("PEROXISOME",
"GAP_JUNCTION",
"FATTY_ACID_METABOLISM",
"VALINE_LEUCINE_AND_ISOLEUCINE_DEGRADATION",
"ALANINE_ASPARTATE_AND_GLUTAMATE_METABOLISM",
"RIBOSOME",
"SPLICEOSOME",
"PROTEASOME")] <- NA
```


```{r}
table_global_2$color <- table_global_2$Stat
table_global_2$color[table_global_2$pvalue > 0.1] <- 0
```

```{r}
ggplot(table_global_2, aes(y = Stat, x = -log10(pvalue), size = Nb, color = color))+geom_point()+ 
  theme(legend.title=element_text(size=2),legend.text=element_text(size=2),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=20),axis.title.x=element_text(size=20),
        axis.text.y=element_text(size=20),axis.text.x=element_text(size=20)) +
  labs(y="Piano Statistic",x="-log10 (Adj.P.Value)")+
  geom_text_repel(aes(label = label),size=2,label.size = 0.1, color = "black", xlim = c(NA, Inf),
    # Do not repel from top or bottom edges.
    ylim = c(-Inf, Inf))+
  scale_colour_gradient2(high = "#800915", mid = "grey", low = "blue")

ggsave("results/figures/pathways_KEGG")
```

```{r}
colors <- c("#b22222", "#177c7c")
```

```{r}
a <- ggplot(table_global_2, aes(y=Name, x = 1, size = Nb, color = sign))+geom_point()+theme_light()+ labs(title="", x="", y="", fill="")+ theme(
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())+ scale_color_manual(values=colors)+ylab("Piano Statistics")+xlab("")+ theme(axis.text.x = element_blank())
a

ggsave(paste0("results/figures/KEGG_spermidine_control_bubble_plot_0.02.pdf"), height = 2, width = 5)
```


```{r}
table_global_2 <- read.csv("/home/flomik/Desktop/Code-PHD/COCOMO_txn/processing/GSEA/hallmark_GSEA_proteomics_organoids_KEGG_all_comparisons.csv")
```

```{r}
table_global_2 <- table_global_2[!table_global_2$comp %in% c("proteomics_organoids_SPD_controls_frac_log2", "proteomics_organoids_hc-like_at-risk_frac_log2"),]
```

```{r}
table_global_2$comp <- gsub("proteomics_organoids_", "", table_global_2$comp)
table_global_2$comp <- gsub("_frac_log2", "", table_global_2$comp)
table_global_2$pvalue <- ifelse(table_global_2$sign == "up", table_global_2$p.adj..dist.dir.up., table_global_2$p.adj..dist.dir.dn.)
table_global_2$Nb <- ifelse(table_global_2$sign == "up", table_global_2$Genes..up., table_global_2$Genes..down.)
table_global_2$Stat <- ifelse(table_global_2$sign == "up", table_global_2$Stat..dist.dir.up., table_global_2$Stat..dist.dir.dn.)

table_global_2$Stat <- ifelse(table_global_2$sign == "up", table_global_2$Stat, -table_global_2$Stat)

table_global_2$Name <- gsub("KEGG_", "", table_global_2$Name)

table_global_2 <- table_global_2[!grepl("DISEASE", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("CANCER", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("CARDIOMYOPATHY", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("INFECTION", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("CARDIOMYOPATHY", table_global_2$Name),]
table_global_2 <- table_global_2[!grepl("CARDIOMYOPATHY", table_global_2$Name),]

table_global_2 <- table_global_2[!table_global_2$Name %in% c("PORPHYRIN_AND_CHLOROPHYLL_METABOLISM", "OLFACTORY_TRANSDUCTION"),]
```


```{r}
write.csv(table_global_2, paste0("results/", name_ana, "_pathways_clean.csv"))
```

```{r}
table_global_2 <- read.csv("/home/flomik/Desktop/Code-PHD/COCOMO_txn/results/GSEA_proteomics_organoids_KEGG_pathways_clean.csv")
table_global_2 <- table_global_2[,c(2, 9,13)]
table_global_2$comp[table_global_2$comp == "hc-like_at-risk_corrected"] <- "at-risk_hc-like_corrected"
write.csv(table_global_2, paste0("results/", name_ana, "_pathways_clean_corrected.csv"))

table_global_2 <- data.frame(dcast(table_global_2, Name ~ comp))
#table_global_2$at.risk_hc.like <- 0
```

```{r}
rownames(table_global_2) <- table_global_2$Name
table_global_2$Name <- NULL
table_global_2[is.na(table_global_2)] <- 0
```

```{r}
pdf("results/figures/Heatmap_proteomics_organoids_frac_log2_pathways_KEGG_FDR_0.2.pdf", width = 5, height = 5)
Heatmap(table_global_2, 
        column_order = colnames(table_global_2)[c(3, 1, 2)],
        row_order = sort(rownames(table_global_2)))
dev.off()
```


