---
title: "Seurat PBMCs"
output: html_notebook
---


### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```


```{r}
library(dplyr)
library(Seurat)
library(patchwork)
```

## data


## Seurat tutorial
tutorial -> https://satijalab.org/seurat/archive/v2.4/pbmc3k_tutorial.html



```{r}
name_ana <- "8k_pbmc_donor"
```


```{r}
pbmc <- readRDS(paste("/home/flomik/Desktop/Code-PHD/data_COCOMO_txn/SCT/", name_ana, "_with_cell_type.rds"))
```

```{r}
library(RColorBrewer)
col <- brewer.pal(9, "Dark2")
col
```

```{r}
col <- c(col, "grey")
```


```{r}
# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(pbmc, reduction = "tsne")
```

```{r}
list_genes <- c("TBCB", "GGCT", "TXLNA", "PLPBP", "LATS1" )
```


```{r}
library(viridis)
col <- c("lightgrey", viridis(9))
```

```{r}
list_x <- list()
list_y <- list()
a <- 1

for (i in list_genes) {
  print(i)
  x <- FeaturePlot(pbmc, features = i, reduction = "tsne", cols = col)
  list_x[[a]] <- x
  ggplot2::ggsave(paste0("/home/flomik/Desktop/Code-PHD/COCOMO_txn/results/figures/SCT/gene_expression/driver_genes/", name_ana, "_feature_plot_", i, ".pdf"), height = 3, width = 3.5)
  y <- VlnPlot(object = pbmc, features = i, cols = col)
  list_y[[a]] <- y
  ggplot2::ggsave(paste0("/home/flomik/Desktop/Code-PHD/COCOMO_txn/results/figures/SCT/gene_expression/driver_genes/", name_ana, "_violon_plot_", i, ".pdf"), height = 3, width = 6)
  
  a <- a + 1
  #pdf(paste0("/home/flomik/Desktop/Code-PHD/COCOMO_txn/results/figures/SCT/gene_expression/", name_ana, "feature_violon_plot_", i, ".pdf"), height = 3, width = 10)
  #grid.arrange(x, y, ncol = 2, nrow = 1)
  #dev.off()
  
}
```



