---
title: "Processing data macrophages"
output: html_notebook
---



### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```

```{r}
library(xlsx)
library(mygene)
library(org.Hs.eg.db)
library(ggplot2)
library(limma)
source("src/usefull_functions.R")
```

## proteomics
1) Normalization per batch
2) Batch correction
3) Filtering

```{r}
name_ana <- "macrophages_COCOMO"
```

```{r}
data <- read.xlsx("data/macrophages/Q-00959_Neogi_NPX_UN.xlsx", 1)
```

```{r}
id_Anoop <- read.xlsx("data/macrophages/Macrophage_Flora.xlsx", 1)
names(id_Anoop)[2] <- "COCOMO_ID"
clinical <- read.csv("processing/clinical_data_clean_with_clusters_and_categories.csv")
clinical <- clinical[,c(2, 3)]
```

```{r}
names(data)[1] <- "Olink.ID"
data <- merge(id_Anoop, data, by = "Olink.ID")
data <- merge(clinical, data, by = "COCOMO_ID", all.y = TRUE)
data$cluster[grep("Hea", data$Proteomics.ID)] <- "Ctrl"
data$cluster <- as.vector(data$cluster)
data$cluster[is.na(data$cluster)] <- "HIV"
```


### distribution
```{r}
data_2 <-as.matrix(data[,-c(1:7)])
hist(data_2 , prob=T)
curve(dnorm(x,mean(data_2),sd(data_2)),add=T,col="red")
```
```{r}
#data[,-c(1:7)] <- scale(data[,-c(1:7)])
```

### distribution
```{r}
data_2 <-as.matrix(data[,-c(1:7)])
hist(data_2 , prob=T)
curve(dnorm(x,mean(data_2),sd(data_2)),add=T,col="red")
```
### PCA before norm
```{r}
pca_data <- data.frame(condition = data$cluster, data[,-c(1:7)])
#pca_data <- pca_data[pca_data$cluster != "HIV",]
pca_data[is.na(pca_data)] <-  0
pca <- prcomp(pca_data[,-1])
df_out <- as.data.frame(pca$x)
df_out$group <- as.factor(pca_data$condition)
x <- project.pca.proportionvariances <- ((pca$sdev^2) / (sum(pca$sdev^2)))*100
a1 <- x[1]
a2 <- x[2]
```

```{r}
ggplot(df_out, aes( x= PC1, y = PC2, color = group))+ geom_point(size = 5, alpha = 0.9, shape = 19)+ 
        theme(legend.title=element_text(size=15),legend.text=element_text(size=12),
              legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
              axis.title.y=element_text(size=15),axis.title.x=element_text(size=15),
              axis.text.y=element_text(size=18),axis.text.x=element_text(size=18))+
        xlab(paste0("PC1: ",round(a1,0),"% variance")) +
        ylab(paste0("PC2: ",round(a2,0),"% variance"))+ 
          theme(axis.title.x = element_text(size=16, face = "bold",color="black"),
                axis.title.y = element_text(size=16, face = "bold",color="black"),
                axis.text = element_text(color="black",size=16, face = "bold"),
                axis.text.x =element_text(color="black",size=16, face = "bold"),
                panel.border = element_blank(),
                axis.ticks.x = element_blank(),
                strip.text.x = element_text(size = 9,color="black"),
                panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
                panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
                panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
                plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
                legend.background=element_rect(fill = alpha("white", 0)))

ggsave("results/figures/PCA_olink_data_macrophages.pdf")
```

```{r}
pca_data <- pca_data[!pca_data$condition %in% c("HIV", "Pool"),]
pca_data$condition <- factor(pca_data$condition, levels = c("Ctrl", "1", "2"))
pca <- prcomp(pca_data[,-1])
df_out <- as.data.frame(pca$x)
df_out$group <- as.factor(pca_data$condition)
x <- project.pca.proportionvariances <- ((pca$sdev^2) / (sum(pca$sdev^2)))*100
a1 <- x[1]
a2 <- x[2]

gg <- data.frame(cluster=factor(df_out$group), x=df_out$PC1, y=df_out$PC2)
rownames(gg) <- rownames(df_out)
centroids <- aggregate(cbind(x,y)~cluster,data=gg,mean)
gg <- merge(gg,centroids,by="cluster",suffixes=c("",".centroid"))
rownames(gg) <- rownames(df_out)
gg$label <- rownames(gg)
```

```{r}
col <- c( "#8ea76b", "#6b8ea7",	"#a7846b")
```


```{r}
ggplot(gg)+
    geom_point(aes(x=x,y=y,color=cluster, fill = cluster), size=3)+
    stat_ellipse(geom = "polygon", aes(x=x,y=y,color=cluster, fill = cluster), alpha = 0.3) +
    geom_point(data=centroids, aes(x=x, y=y, color=cluster, fill = cluster), size = 5, alpha = 0.9, shape = 19)+ 
    geom_segment(aes(x=x.centroid, y=y.centroid, xend=x, yend=y, color=cluster))+
    theme(legend.title=element_text(size=15),legend.text=element_text(size=12),
            legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
            axis.title.y=element_text(size=15),axis.title.x=element_text(size=15),
            axis.text.y=element_text(size=18),axis.text.x=element_text(size=18))+
      xlab(paste0("PC1: ",round(a1,0),"% variance"))+
      ylab(paste0("PC2: ",round(a2,0),"% variance"))+ 
        theme(axis.title.x = element_text(size=16, face = "bold",color="black"),
              axis.title.y = element_text(size=16, face = "bold",color="black"),
              axis.text = element_text(color="black",size=16, face = "bold"),
              axis.text.x =element_text(color="black",size=16, face = "bold"),
              panel.border = element_blank(),
              axis.ticks.x = element_blank(),
              strip.text.x = element_text(size = 9,color="black"),
              panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
              panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
              panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
              plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
              legend.background=element_rect(fill = alpha("white", 0)))+ scale_color_manual(values = col)+ scale_fill_manual(values = col)


path_fig <- paste0("results/figures/PCA_olink_macrophages.pdf")
ggsave(path_fig, height = 4, width = 5)
```



      

```{r}
ggplot(df_out, aes( x= PC1, y = PC2, color = group))+ geom_point(size = 5, alpha = 0.9, shape = 19)+ 
        theme(legend.title=element_text(size=15),legend.text=element_text(size=12),
              legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
              axis.title.y=element_text(size=15),axis.title.x=element_text(size=15),
              axis.text.y=element_text(size=18),axis.text.x=element_text(size=18))+
        xlab(paste0("PC1: ",round(a1,0),"% variance")) +
        ylab(paste0("PC2: ",round(a2,0),"% variance"))+ 
          theme(axis.title.x = element_text(size=16, face = "bold",color="black"),
                axis.title.y = element_text(size=16, face = "bold",color="black"),
                axis.text = element_text(color="black",size=16, face = "bold"),
                axis.text.x =element_text(color="black",size=16, face = "bold"),
                panel.border = element_blank(),
                axis.ticks.x = element_blank(),
                strip.text.x = element_text(size = 9,color="black"),
                panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
                panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
                panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
                plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
                legend.background=element_rect(fill = alpha("white", 0)))+ scale_color_manual(values = col)+ scale_fill_manual(values = col)

ggsave("results/figures/PCA_olink_data_macrophages.pdf")
```

## umap
```{r}
library(umap)

prot.labels <- pca_data$condition
prot.umap = umap(pca_data[,-1])
prot.umap
  
data <- prot.umap$data
layout <- prot.umap$layout
data_umap <- cbind(data, layout)
x = ncol(data_umap)
y = ncol(data_umap)-1
print(x)
print(y)
colnames(data_umap)[y:x] <- c("UMAP1", "UMAP2")
data_umap <-data.frame(data_umap)
  
data_umap %>% 
  mutate(Condition = prot.labels) %>%
  ggplot(aes(UMAP1, UMAP2), color = Condition, fill = Condition)+ geom_point(size = 5, alpha = 1, shape = 21, color = "black", aes(fill = factor(Condition)))+ theme_minimal()+ 
      theme(legend.title=element_text(size=10),legend.text=element_text(size=10),
            legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
            axis.title.y=element_text(size=16, color = "black", face="bold"),axis.title.x=element_text(size=16, color = "black", face="bold"),
            axis.text.y=element_text(size=14, color = "black"),axis.text.x=element_text(size=14, color = "black"))+ scale_color_manual(values = col)+ scale_fill_manual(values = col)
  
  ggsave(paste0("results/figures/UMAP_olink_macrophages.pdf"), width = 6, height = 4)
```



```{r}
condition <- pca_data$condition
condition <- as.vector(condition)
condition[condition != "Ctrl"] <- paste0("C", condition[condition != "Ctrl"])
design <- model.matrix( ~ 0 + condition)
colnames(design) <- gsub("condition", "", colnames(design))
fit <- lmFit(t(pca_data[,-c(1)]), design)
```



```{r}
list_comp <- unique(condition)
list_pair <- data.frame(t(combn(list_comp,2)))
list_pair$comp <- paste0(list_pair$X1, "-", list_pair$X2)
comp <- list_pair$comp
names(comp) <- gsub("roup", "", comp)
comp
```

```{r}
cont.matrix <- makeContrasts(G1_G2 = comp[1], G1_CT = comp[2], G2_CT = comp[3],levels=design)

fit.cont <- contrasts.fit(fit, cont.matrix)
fit.cont <- eBayes(fit.cont)
```

```{r}
top_table <- data.frame(BIOCHEMICAL = NA, logFC= NA, P.Value= NA, adj.P.Val= NA, Comp= NA)

for (i in 1:length(comp)) {
  top_table_1 <- topTable(fit.cont, coef=i, adjust="BH", n = Inf, sort.by = "P")
  top_table_1$Comp <- comp[i]
  top_table_1$BIOCHEMICAL <- rownames(top_table_1)
  top_table_1 <- top_table_1[,c(8, 1, 4, 5, 7)]
  write.table(top_table_1$BIOCHEMICAL[top_table_1$adj.P.Val < 0.1], paste0("processing/MSEA/LIMMA_macrophages_olink_", comp[i],".txt"), quote = FALSE, row.names = F)
  top_table <- rbind(top_table, top_table_1)
}

top_table <- top_table[complete.cases(top_table),]
path_table <- paste0("results/macrophages/LIMMA_macrophages_olink_proteomics.csv")

print(path_table)
write.csv(top_table, file =path_table)

DF_top_table <-top_table[top_table$adj.P.Val < 0.1, ]

path_results <- paste0("results/macrophages/LIMMA_macrophages_olink_filt.csv")

write.table(DF_top_table, file = path_results)

path_results <- paste0("results/macrophages/LIMMA_macrophages_olink_filt.xlsx")

write.xlsx(DF_top_table, file = path_results)

table(DF_top_table$Comp)
```
```{r}
mac <- read.xlsx("data/macrophages/M1 and M2 marker gene list_AG Savai_March 2022.xlsx", 1)
mac_M1 <- as.vector(mac$Gene.Symbol)
mac_M1 <- gsub(" \\(.*", "", mac_M1)

mac_M1[mac_M1 == "ACOD1/IRG1"] <- "ACOD1"
mac_M1[mac_M1 == "NOS2\\iNOS"] <- "NOS2"
mac_M1[mac_M1 == "CXCL8\\IL8"] <- "CXCL8"
mac_M1 <- c("IL8", "IRG1", mac_M1)

mac_M2 <- as.vector(mac$Gene.Symbol.1)
mac_M2[mac_M2 == "MRC1\\CD206"] <- "MRC1"
mac_M2 <- c("CD206", mac_M2)
```
M2 <- CD206
M1 <- IRG1, IL8

```{r}
library(scales)
library(ggpubr)
library(ggrepel)
```

## volcano plots
```{r}
top_table_1 <- top_table[top_table$Comp == "C1-Ctrl",]
top_table_2 <- top_table[top_table$Comp == "C2-Ctrl",]
top_table_3 <- top_table[top_table$Comp == "C1-C2",]
```

## volcano plot
```{r}
tt <- top_table_1
tt$BIOCHEMICAL[!tt$BIOCHEMICAL %in% c(as.vector(mac_M1), as.vector(mac_M2))] <- NA
tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M1 & !is.na(tt$BIOCHEMICAL)] <- paste0(tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M1 & !is.na(tt$BIOCHEMICAL)], " (M1)")
tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M2 & !is.na(tt$BIOCHEMICAL)] <- paste0(tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M2 & !is.na(tt$BIOCHEMICAL)], " (M2)")


name_ana <- unique(tt$Comp)
tt$color <- NA

for (i in 1:nrow(tt)){
  if(tt[i, 2] > 0.5 & tt[i, 4] < 0.1){
    print(tt[i, 1])
    tt[i, ncol(tt)] <- "up_regulated"
  }
  if(tt[i, 2] < -0.5 & tt[i, 4] < 0.1){
    print(tt[i, 1])
    tt[i, ncol(tt)] <- "down_regulated"
  }
  if(tt[i, 4] > 0.1){
    tt[i, ncol(tt)] <- "NS"
    #tt[i, 1] <- NA
  }
}

tt$color[is.na(tt$color)] <- "significant"
#tt$Gene_name[tt$color == "significant"] <- NA
cols <- c("up_regulated" = "#f1c232", "down_regulated" = "#86b7e8", "NS" = "grey", "significant" = "#586c6e")

vol <- ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val), colour = color, size = abs(logFC)))+ 
  geom_point(alpha = 1, na.rm = T)+ 
  theme(legend.title=element_text(size=2),legend.text=element_text(size=2),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=25),axis.title.x=element_text(size=25),
        axis.text.y=element_text(size=25),axis.text.x=element_text(size=25)) +
  labs(x="Log2 Fold Change",y="-log10 (adj.P.Val)")+
  geom_text_repel(aes(label = BIOCHEMICAL),size=2,label.size = 0.1, color = "black", xlim = c(NA, Inf),
    # Do not repel from top or bottom edges.
    ylim = c(-Inf, Inf))+ theme_classic()+ 
  geom_hline(yintercept=-log10(0.1), linetype="dashed", color = "black")+
geom_vline(xintercept= -0.5, linetype="dashed", color = "black")+
geom_vline(xintercept= 0.5, linetype="dashed", color = "black")+scale_color_manual(values = cols)

print(vol)
path_fig <- paste0("results/figures/volcano_plots/", name_ana, "_volcano_plot.pdf")
ggsave(path_fig, width = 6, height = 3)
  
```

```{r}
tt <- top_table_2
tt$BIOCHEMICAL[!tt$BIOCHEMICAL %in% c(as.vector(mac_M1), as.vector(mac_M2))] <- NA
tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M1 & !is.na(tt$BIOCHEMICAL)] <- paste0(tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M1 & !is.na(tt$BIOCHEMICAL)], " (M1)")
tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M2 & !is.na(tt$BIOCHEMICAL)] <- paste0(tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M2 & !is.na(tt$BIOCHEMICAL)], " (M2)")


name_ana <- unique(tt$Comp)
tt$color <- NA

for (i in 1:nrow(tt)){
  if(tt[i, 2] > 0.5 & tt[i, 4] < 0.1){
    print(tt[i, 1])
    tt[i, ncol(tt)] <- "up_regulated"
  }
  if(tt[i, 2] < -0.5 & tt[i, 4] < 0.1){
    print(tt[i, 1])
    tt[i, ncol(tt)] <- "down_regulated"
  }
  if(tt[i, 4] > 0.1){
    tt[i, ncol(tt)] <- "NS"
    #tt[i, 1] <- NA
  }
}

tt$color[is.na(tt$color)] <- "significant"
#tt$Gene_name[tt$color == "significant"] <- NA
cols <- c("up_regulated" = "#f1c232", "down_regulated" = "#86b7e8", "NS" = "grey", "significant" = "#586c6e")

vol <- ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val), colour = color, size = abs(logFC)))+ 
  geom_point(alpha = 1, na.rm = T)+ 
  theme(legend.title=element_text(size=2),legend.text=element_text(size=2),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=25),axis.title.x=element_text(size=25),
        axis.text.y=element_text(size=25),axis.text.x=element_text(size=25)) +
  labs(x="Log2 Fold Change",y="-log10 (adj.P.Val)")+
  geom_text_repel(aes(label = BIOCHEMICAL),size=2,label.size = 0.1, color = "black", xlim = c(NA, Inf),
    # Do not repel from top or bottom edges.
    ylim = c(-Inf, Inf))+ theme_classic()+ 
  geom_hline(yintercept=-log10(0.1), linetype="dashed", color = "black")+
geom_vline(xintercept= -0.5, linetype="dashed", color = "black")+
geom_vline(xintercept= 0.5, linetype="dashed", color = "black")+scale_color_manual(values = cols)

print(vol)
path_fig <- paste0("results/figures/volcano_plots/", name_ana, "_volcano_plot.pdf")
ggsave(path_fig, width = 6, height = 3)
  
```


```{r}
tt <- top_table_3
tt$BIOCHEMICAL[!tt$BIOCHEMICAL %in% c(as.vector(mac_M1), as.vector(mac_M2))] <- NA
tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M1 & !is.na(tt$BIOCHEMICAL)] <- paste0(tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M1 & !is.na(tt$BIOCHEMICAL)], " (M1)")
tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M2 & !is.na(tt$BIOCHEMICAL)] <- paste0(tt$BIOCHEMICAL[tt$BIOCHEMICAL %in% mac_M2 & !is.na(tt$BIOCHEMICAL)], " (M2)")


name_ana <- unique(tt$Comp)
tt$color <- NA

for (i in 1:nrow(tt)){
  if(tt[i, 2] > 0.5 & tt[i, 4] < 0.1){
    print(tt[i, 1])
    tt[i, ncol(tt)] <- "up_regulated"
  }
  if(tt[i, 2] < -0.5 & tt[i, 4] < 0.1){
    print(tt[i, 1])
    tt[i, ncol(tt)] <- "down_regulated"
  }
  if(tt[i, 4] > 0.1){
    tt[i, ncol(tt)] <- "NS"
    #tt[i, 1] <- NA
  }
}

tt$color[is.na(tt$color)] <- "significant"
#tt$Gene_name[tt$color == "significant"] <- NA
cols <- c("up_regulated" = "#f1c232", "down_regulated" = "#86b7e8", "NS" = "grey", "significant" = "#586c6e")

vol <- ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val), colour = color, size = abs(logFC)))+ 
  geom_point(alpha = 1, na.rm = T)+ 
  theme(legend.title=element_text(size=2),legend.text=element_text(size=2),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=25),axis.title.x=element_text(size=25),
        axis.text.y=element_text(size=25),axis.text.x=element_text(size=25)) +
  labs(x="Log2 Fold Change",y="-log10 (adj.P.Val)")+
  geom_text_repel(aes(label = BIOCHEMICAL),size=2,label.size = 0.1, color = "black", xlim = c(NA, Inf),
    # Do not repel from top or bottom edges.
    ylim = c(-Inf, Inf))+ theme_classic()+ 
  geom_hline(yintercept=-log10(0.1), linetype="dashed", color = "black")+
geom_vline(xintercept= -0.5, linetype="dashed", color = "black")+
geom_vline(xintercept= 0.5, linetype="dashed", color = "black")+scale_color_manual(values = cols)+ylim(0, 0.00015)

print(vol)
path_fig <- paste0("results/figures/volcano_plots/", name_ana, "_volcano_plot.pdf")
ggsave(path_fig, width = 6, height = 3)
  
```

```{r}
dge <- top_table[,c(1,2, 4, 5)]
dge <- dge[dge$adj.P.Val < 0.01,]
dge <- dge[order(match(dge[,1],colnames(pca_data))),]
list_olink <- dge$BIOCHEMICAL
```

## ven diagram
```{r}
library(venneuler)

pdf("results/figures/ven_diagramme_olink_overlap.pdf")
MyVenn <- venneuler(c(A =14, B= 28,"A&B"=13))
plot(MyVenn)

text(0.535,0.51,"13")
text(0.78,0.51,"1")
text(0.20,0.51,"15")
dev.off()

```

```{r}
data_prot_6 <- pca_data[,colnames(pca_data) %in% c("condition", as.vector(list_olink))]
condition <- pca_data$condition
condition <- as.vector(condition)

condition[condition == 1] <- "HC-like"
condition[condition == 2] <- "At-risk"

condition <- factor(condition, levels = c("Ctrl", "HC-like", "At-risk"))

data_prot_6 <- data_prot_6[,-1]
data_prot_6 <- data.frame(t(data_prot_6))
```



```{r}
pca_data <- data.frame(condition = condition, t(data_prot_6))
pca <- prcomp(pca_data[,-1])
df_out <- as.data.frame(pca$x)
df_out$group <- as.factor(pca_data$condition)
x <- project.pca.proportionvariances <- ((pca$sdev^2) / (sum(pca$sdev^2)))*100
a1 <- x[1]
a2 <- x[2]

gg <- data.frame(cluster=factor(df_out$group), x=df_out$PC1, y=df_out$PC2)
rownames(gg) <- rownames(df_out)
centroids <- aggregate(cbind(x,y)~cluster,data=gg,mean)
gg <- merge(gg,centroids,by="cluster",suffixes=c("",".centroid"))
rownames(gg) <- rownames(df_out)
gg$label <- rownames(gg)
```

```{r}
col <- c( "#8ea76b", "#6b8ea7",	"#a7846b")
```


```{r}
ggplot(gg)+
    geom_point(aes(x=x,y=y,color=cluster, fill = cluster), size=3)+
    stat_ellipse(geom = "polygon", aes(x=x,y=y,color=cluster, fill = cluster), alpha = 0.3) +
    geom_point(data=centroids, aes(x=x, y=y, color=cluster, fill = cluster), size = 5, alpha = 0.9, shape = 19)+ 
    geom_segment(aes(x=x.centroid, y=y.centroid, xend=x, yend=y, color=cluster))+
    theme(legend.title=element_text(size=15),legend.text=element_text(size=12),
            legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
            axis.title.y=element_text(size=15),axis.title.x=element_text(size=15),
            axis.text.y=element_text(size=18),axis.text.x=element_text(size=18))+
      xlab(paste0("PC1: ",round(a1,0),"% variance"))+
      ylab(paste0("PC2: ",round(a2,0),"% variance"))+ 
        theme(axis.title.x = element_text(size=16, face = "bold",color="black"),
              axis.title.y = element_text(size=16, face = "bold",color="black"),
              axis.text = element_text(color="black",size=16, face = "bold"),
              axis.text.x =element_text(color="black",size=16, face = "bold"),
              panel.border = element_blank(),
              axis.ticks.x = element_blank(),
              strip.text.x = element_text(size = 9,color="black"),
              panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
              panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
              panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
              plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
              legend.background=element_rect(fill = alpha("white", 0)))+ scale_color_manual(values = col)+ scale_fill_manual(values = col)


path_fig <- paste0("results/figures/PCA_olink_macrophages_filtered_29.pdf")
ggsave(path_fig, height = 4, width = 5)
```
## umap
```{r}
library(dplyr)
library(umap)

prot.labels <- pca_data$condition
prot.umap = umap(pca_data[,-1])
prot.umap
  
data <- prot.umap$data
layout <- prot.umap$layout
data_umap <- cbind(data, layout)
x = ncol(data_umap)
y = ncol(data_umap)-1
print(x)
print(y)
colnames(data_umap)[y:x] <- c("UMAP1", "UMAP2")
data_umap <-data.frame(Condition = prot.labels, data_umap)
  
ggplot(data_umap, aes(UMAP1, UMAP2))+ 
  geom_point(size = 5, alpha = 1, shape = 21, color = "black", aes(fill = factor(Condition)))+
  stat_ellipse(type = "norm", geom = "polygon", aes(fill = Condition, color = Condition), alpha = 0.25)+ 
  theme_minimal()+ 
      theme(legend.title=element_text(size=10),legend.text=element_text(size=10),
            legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
            axis.title.y=element_text(size=16, color = "black", face="bold"),axis.title.x=element_text(size=16, color = "black", face="bold"),
            axis.text.y=element_text(size=14, color = "black"),axis.text.x=element_text(size=14, color = "black"))+ scale_color_manual(values = col)+ scale_fill_manual(values = col)
  
  ggsave(paste0("results/figures/UMAP_olink_macrophages-filtered_29.pdf"), width = 6, height = 4)
```

## heatmap
```{r}
data_prot_6 <- data.frame(t(scale(t(data_prot_6))))
```

```{r}
max(data_prot_6$X5)
```


```{r}
library(circlize)
col_fun1 = colorRamp2(c(-3,-1, -0.5, 0, 0.5, 1, 3), c("#1e90ff","#2676d0" ,"#275ea2","black","#a39a21","#d0c521","#fff21e"))
col_fun_2 = colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))
```

```{r}
col <- c( "#8ea76b", "#6b8ea7",	"#a7846b")
```

```{r}
library(ComplexHeatmap)
```

```{r}
dge$logFC <- dge$logFC
```

```{r}
dge_1 <- dge[dge$Comp == "C1-Ctrl",]
dge_2 <- dge[dge$Comp == "C2-Ctrl",]
```

```{r}
data_prot_6$BIOCHEMICAL <- rownames(data_prot_6)
```

```{r}
data_prot_6 <- merge(dge_1, data_prot_6, by = "BIOCHEMICAL", all.y = TRUE)
data_prot_6 <- merge(dge_2, data_prot_6, by = "BIOCHEMICAL", all.y = TRUE)
```
```{r}
rownames(data_prot_6) <- data_prot_6$BIOCHEMICAL
```

```{r}
data_prot_6 <- data_prot_6[!is.na(data_prot_6$adj.P.Val.x) & is.na(data_prot_6$adj.P.Val.y),]
```

```{r}
condition <- factor(condition, levels = c("Ctrl", "HC-like", "At-risk"))
```

```{r}
pdf("results/figures/Heatmap_macrophages_olink_Ctrl_vs_clusters_0_001.pdf", width = 6, height = 4)
ht = Heatmap(data_prot_6[,-c(1:7)], 
             #column_order = sort(colnames(t(data_prot_6[,-c(1:5)]))),  
             col = col_fun1, 
             show_column_names = FALSE, 
             show_row_names = TRUE,
             column_split = condition, 
             #row_split = data_2$under_group, 
             #column_title = c("Ctrl",1, 2), 
             #column_title_gp = gpar(fill = col), 
             border = FALSE, 
             column_gap = unit(2, "mm"), 
             right_annotation = rowAnnotation(C2_Ctrl = data_prot_6$logFC.x,
                                              col = list(C2_Ctrl = col_fun_2), show_legend = TRUE),
             top_annotation = HeatmapAnnotation(cluster = condition,
                                              col = list(cluster = c("Ctrl" = col[1], "HC-like" = col[2], "At-risk" = col[3])), show_legend = TRUE)
             )
draw(ht)
dev.off()

ht
```

