---
title: "Prepare cybersort mixture file"
output: html_notebook
---


### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```

### load packages
```{r}
library(mygene)
library(xlsx)
library(org.Hs.eg.db)
library(ggplot2)
library(reshape2)
```

```{r}
fractions <- read.delim("data/CIBERSORT/10_types/CIBERSORTxGEP_Job34_Fractions.txt")
fractions <- fractions[-1,-c(24:26)]
rownames(fractions) <- fractions$Mixture
fractions$Mixture <- NULL
```

```{r}
fractions$User <- rownames(fractions)
```

```{r}
cluster <- read.csv("processing/clinical_data_clean_with_clusters_and_categories.csv")
cluster <- cluster[,c(4,3)]
fractions <- merge(cluster, fractions, by = "User")
fractions$User <- NULL
```

```{r}
phylum_colors <- c("#5F7FC7","#DA5724", "#508578", "#CD9BCD",
   "#AD6F3B", "#673770","#D14285", "#652926", "#C84248", 
  "#8569D5", "orange", "#CBD588", "#edf2ef", "#5E738F","#D1A33D", "#8A7C64")
```


```{r}
data_factor <- fractions
```

```{r}
data_factor <- data_factor[, !colnames(data_factor) %in% c("Plasma.cells", colnames(data_factor)[grepl("Dendritic.cells.resting", colnames(data_factor))], colnames(data_factor)[grepl("Macro", colnames(data_factor))], colnames(data_factor)[grepl("Mast", colnames(data_factor))])]
fractions_2 <- aggregate(. ~ cluster, data=data_factor, FUN=mean)
fractions_3 <- melt(fractions_2)
```

```{r}
names(data_factor)
```

```{r}
table_fraction <- data.frame(cell_type = NA, p_HC_C1 = NA, p_HC_C2 = NA, p_C1_C2 = NA)
j = 1

for (i in 2:ncol(fractions)) {
  x <- pairwise.wilcox.test(fractions[,i], fractions$cluster, p.adj = "fdr")
  table_fraction_2 <- data.frame(cell_type = names(fractions)[i], p_HC_C1 = x$p.value[2], p_HC_C2 = x$p.value[4], p_C1_C2 = x$p.value[1])
  table_fraction <- rbind(table_fraction_2, table_fraction)
}

table_fraction$FDR <- p.adjust(table_fraction$p_C1_C2, method = "fdr")
table_fraction <- table_fraction[complete.cases(table_fraction),]
write.csv(table_fraction, "results/CIBERSORT_differences_proportions.csv")
```

```{r}
fractions_3$cluster <- factor(fractions_3$cluster, levels = c("Ctrl", 1, 2))
```

```{r}
fractions_3$variable <- as.vector(fractions_3$variable)

fractions_3$variable_2 <- fractions_3$variable
fractions_3$variable_2 <- gsub("cells\\..*", "cells\\.", fractions_3$variable_2)
```

## mean barplot by cluster
```{r}
m1 <- ggplot(fractions_3, aes(fill=variable, y=value, x=cluster)) + 
    geom_bar(position="fill", stat="identity", alpha= 0.6)+ylab("")+ theme_void()+ 
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          axis.text = element_blank(),
          panel.border = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text.x = element_text(size = 7,color="black"),
          legend.position="bottom",
          axis.text.x = element_text(size = 7,color="black")
          )+
  theme(legend.position = "right")+scale_fill_manual(values = c(phylum_colors, "red", "blue", "green", "pink", "grey","black")) + geom_text(aes(label=ifelse(value >= 0.10, paste0(round(value*100, 0), "%"),"")), position=position_stack(vjust=0.5), colour="black")

m1

ggsave("/home/flomik/Desktop/Code-PHD/IFN_Covid_multiomics/results/figures/CIBERSORT_proportions_conditions.pdf", height = 6, width = 10)
```
```{r}
fractions_3
```
```{r}
fractions_3$cluster <- factor(fractions_3$cluster, levels = c("Ctrl", 1, 2))
```



```{r}
fractions_4 <- fractions_3[fractions_3$value > 0,]
```

```{r}
m1 <- ggplot(fractions_4, aes(y=variable, x=cluster, size = value, col = value))+geom_point()+
  scale_size_continuous(range = c(2,6))+
   scale_colour_gradient(low = "#3d7b20", high = "#152a0b", na.value = NA)+theme_classic()+theme(axis.line=element_blank(),
      axis.ticks=element_blank(),
      axis.title.x=element_blank(),
      axis.title.y=element_blank(),
      panel.background=element_blank(),
      panel.border=element_blank(),
      panel.grid.major=element_blank(),
      panel.grid.minor=element_blank(),
      plot.background=element_blank())
m1
ggsave("results/figures/proportions_cell_types_bulk.pdf", width = 4, height = 3)
```


