---
title: "R Notebook"
output: html_notebook
---

### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```

```{r}
library(xlsx)
library(gplots)
library(ComplexHeatmap)
library(circlize)
library(limma)
library("colorspace")
library(ggplot2)
library(dplyr)
library(scales)
```

```{r}
col <- c( "#005900", "#878782",	"#761212")
```

```{r}
list_mic_met <- read.delim("data/MDM/MDM_clean_list_2_Postler.txt")
list_mic_met$Line <- NULL
```

```{r}
clinical <- read.csv("processing/clinical_data_clean_with_clusters_and_categories.csv")
clinical$X.1 <- NULL
names(clinical)[2] <- "COCOMO_ID"
```

```{r}
data_met <- read.csv("processing/COCOMO_metabolomics_log2_norm_filt.csv", row.names = 1, check.names = FALSE)
data_met <- data.frame(t(data_met))
metabolites <- rownames(data_met)
data_met <- data.frame(t(data_met))

rownames(data_met) <- gsub("X", "", rownames(data_met))
colnames(data_met) <- metabolites
data_met$COCOMO_ID <- rownames(data_met)
```

```{r}
pca_data <- merge(clinical, data_met, by = "COCOMO_ID")
data_met <- pca_data
```

```{r}
dge <- read.csv("results/LIMMA/model_2_LIMMA_results_metabolites_with_HC_filt.csv", sep = " ")
dge_mic_met <- dge[dge$BIOCHEMICAL %in% list_mic_met$BIOCHEMICAL,]
```

```{r}
data_sign <- data_met[, colnames(data_met) %in% c("cluster", as.vector(dge_mic_met$BIOCHEMICAL))]
data_sign$cluster <- factor(data_sign$cluster, levels = c("Ctrl", 1, 2))
```

```{r}
pca <- prcomp(data_sign[, -1], scale. = TRUE)
df_out <- as.data.frame(pca$x)
df_out$group <- as.factor(data_sign$cluster)
  
x <- project.pca.proportionvariances <- ((pca$sdev^2) / (sum(pca$sdev^2)))*100
a1 <- x[1]
a2 <- x[2]

gg <- data.frame(cluster=factor(df_out$group), x=df_out$PC1, y=df_out$PC2)
  centroids <- aggregate(cbind(x,y)~cluster,data=gg,mean)
  gg <- merge(gg,centroids,by="cluster",suffixes=c("",".centroid"))
  
ggplot(gg)+
    geom_point(aes(x=x,y=y,color=cluster, fill = cluster), size=3)+
    stat_ellipse(geom = "polygon", aes(x=x,y=y,color=cluster, fill = cluster), alpha = 0.3) +
    geom_point(data=centroids, aes(x=x, y=y, color=cluster, fill = cluster), size = 5, alpha = 0.9, shape = 19)+ 
    geom_segment(aes(x=x.centroid, y=y.centroid, xend=x, yend=y, color=cluster))+
    theme(legend.title=element_text(size=15),legend.text=element_text(size=12),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=15),axis.title.x=element_text(size=15),
        axis.text.y=element_text(size=18),axis.text.x=element_text(size=18))+
    xlab(paste0("PC1: ",round(a1,0),"% variance"))+
    ylab(paste0("PC2: ",round(a2,0),"% variance"))+ 
    theme(axis.title.x = element_text(size=16, face = "bold",color="black"),
          axis.title.y = element_text(size=16, face = "bold",color="black"),
          axis.text = element_text(color="black",size=16, face = "bold"),
          axis.text.x =element_text(color="black",size=16, face = "bold"),
          panel.border = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text.x = element_text(size = 9,color="black"),
          panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
          panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
          panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
          plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
          legend.background=element_rect(fill = alpha("white", 0)))+ scale_color_manual(values=col)+ scale_fill_manual(values=col)

path_fig <- paste0("results/figures/PCA_significant_microbiome_derived_metabolomics_correlated_centroids.pdf")
dev.copy(pdf, path_fig, height = 4, width = 6)
dev.off()
```
```{r}
pca <- prcomp(data_sign[, -1], scale. = TRUE)
df_out <- as.data.frame(pca$x)
df_out$group <- as.factor(data_sign$cluster)
  
x <- project.pca.proportionvariances <- ((pca$sdev^2) / (sum(pca$sdev^2)))*100
a1 <- x[1]
a2 <- x[2]

gg <- data.frame(cluster=factor(df_out$group), x=df_out$PC1, y=df_out$PC2)
  centroids <- aggregate(cbind(x,y)~cluster,data=gg,mean)
  gg <- merge(gg,centroids,by="cluster",suffixes=c("",".centroid"))
  
ggplot(df_out)+
    geom_point(aes(x=PC1,y=PC2,color=group, fill = group), size=3) +
    theme(legend.title=element_text(size=15),legend.text=element_text(size=12),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=15),axis.title.x=element_text(size=15),
        axis.text.y=element_text(size=18),axis.text.x=element_text(size=18))+
    xlab(paste0("PC1: ",round(a1,0),"% variance"))+
    ylab(paste0("PC2: ",round(a2,0),"% variance"))+ 
    theme(axis.title.x = element_text(size=16, face = "bold",color="black"),
          axis.title.y = element_text(size=16, face = "bold",color="black"),
          axis.text = element_text(color="black",size=16, face = "bold"),
          axis.text.x =element_text(color="black",size=16, face = "bold"),
          panel.border = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text.x = element_text(size = 9,color="black"),
          panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
          panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
          panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
          plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
          legend.background=element_rect(fill = alpha("white", 0)))+ scale_color_manual(values=col)+ scale_fill_manual(values=col)

path_fig <- paste0("results/figures/PCA_significant_microbiome_derived_metabolomics_correlated.pdf")
dev.copy(pdf, path_fig, height = 4, width = 6)
dev.off()
```

## Heatmap
```{r}
table_DGE <- dge_mic_met
data <- pca_data
data$X <- NULL
```

```{r}
cluster <- data$cluster
data_2 <- data.frame(t(data[,-c(1:47)]))
data_2$BIOCHEMICAL <- rownames(data_2)
data_2 <- merge(table_DGE, data_2, by = "BIOCHEMICAL")
data_2$Group <- NA
names(data_2)[1] <- "Metabolite"
data_2$Group[grepl("acetate", data_2$Metabolite)] <- "acetate derivates"
data_2$Group[grepl("butyrate", data_2$Metabolite)] <- "butyrate derivates"
data_2$Group[grepl("kynurenine", data_2$Metabolite)] <- "kynurenine derivates"
data_2$Group[grepl("propionate", data_2$Metabolite)] <- "propionate derivates"
data_2$Group[grepl("indole", data_2$Metabolite)] <- "indole derivates"
names(data_2)[1] <- "BIOCHEMICAL"
data_2 <- merge(list_mic_met, data_2, by = "BIOCHEMICAL")

data_2$SUB.PATHWAY <- as.vector(data_2$SUB.PATHWAY)
list_other <- names(table(data_2$SUB.PATHWAY) > 1)

data_2$SUB.PATHWAY[!data_2$SUB.PATHWAY %in% c("Lipid Fatty Acid Metabolism (Acyl Carnitine, Short Chain)","Tryptophan Metabolism", "Benzoate Metabolism", "Polyamine Metabolism", "Primary Bile Acid Metabolism", "Secondary Bile Acid Metabolism")] <- "Others"
```

## heatmap metabolites
```{r}
data_3 <- data.frame(t(data_2[,-c(1:11, 188)]))
data_3 <- data.frame(scale(data_3))
max(data_3)
min(data_3)
```

```{r}
colnames(data_3) <- data_2$BIOCHEMICAL
```

```{r}
#data_3[data_3 > 3] <- 3
#data_3[data_3 < -3] <- -3
```

```{r}
col_fun1 = colorRamp2(c(-3,-1.2, -1, 0,1, 1.2,3), c("#7F7F00","#B2B200" ,"#E5E500","white","#BF7FBF","#993299","#590059"))
col_fun_2 = colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))
```

```{r}
group_GSSM <- read.csv("processing/subgroups_GSSM.csv")
```

```{r}
pdf("results/figures/microbiome_derived_metabolites_two_new_clusters", width = 16, height = 7)
ht = Heatmap(t(data_3), col = col_fun1, show_column_names = FALSE, column_split = cluster, row_split = data_2$under_group, column_title = c("Ctrl",1, 2), 
             column_title_gp = gpar(fill = col), border = FALSE, column_gap = unit(2, "mm"), 
             right_annotation = rowAnnotation(C2vsC1 = data_2$logFC,
                                              Pathway = data_2$SUPER.PATHWAY,
                                              Sub_Pathway = data_2$SUB.PATHWAY,
                                              Under_group = data_2$under_group,
                                              col = list(C2vsC1 = col_fun_2), show_legend = TRUE))
draw(ht)
dev.off()
```


