---
title: "olink analysis"
output: html_notebook
---


### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```

### load packages
```{r}
library(DESeq2)
library(dplyr)
library(SNFtool)
library(xlsx)
library(ggplot2)
library(corrr)
library(mygene)
library(edgeR)
library(piano)
```

```{r}
col <- c( "#8ea76b", "#6b8ea7",	"#a7846b")
```

```{r}
library(ggplot2)
library(ggpubr)
```


### clinical paraolinkers
```{r}
clinical <- read.csv("processing/clinical_data_clean_paper_4.csv", row.names = 2)
clinical$X.1 <- NULL
clinical$COCOMO_ID <- rownames(clinical)
```

### olink
```{r}
data <- read.csv("processing/olink_data_new_ids.csv", row.names = 1)
data$Condition <- NULL
```



```{r}
data$COCOMO_ID <- rownames(data)
pca_data <- merge(clinical, data, by = "COCOMO_ID")
```

```{r}
group <- as.factor(pca_data$cluster)
design <- model.matrix( ~ 0 + group)
```

```{r}
fit <- lmFit(t(pca_data[,-c(1:165)]), design)
```

```{r}
list_comp <- c(paste0("group",2:1), "groupCtrl")
list_pair <- data.frame(t(combn(list_comp,2)))
list_pair$comp <- paste0(list_pair$X1, "-", list_pair$X2)
comp <- list_pair$comp
names(comp) <- gsub("roup", "", comp)
```

```{r}
cont.matrix <- makeContrasts(G2_G1 = comp[1],
                             levels=design)

fit.cont <- contrasts.fit(fit, cont.matrix)
fit.cont <- eBayes(fit.cont)
```

```{r}
top_table <- data.frame(BIOCHEMICAL = NA, logFC= NA, P.Value= NA, adj.P.Val= NA, Comp= NA)

top_table_1 <- topTable(fit.cont, coef=1, adjust="BH", n = Inf, sort.by = "P")
top_table_1$Comp <- comp[1]
top_table_1$BIOCHEMICAL <- rownames(top_table_1)
top_table_1 <- top_table_1[,c(8, 1, 4, 5, 7)]
write.table(top_table_1$BIOCHEMICAL[top_table_1$adj.P.Val < 0.1], paste0("processing/MSEA/model_1_olink_", comp[1],".txt"), quote = FALSE, row.names = F)

top_table <- top_table_1[complete.cases(top_table_1),]
path_table <- paste0("results/LIMMA/model_1_LIMMA_results_olink_with_HC.csv")

print(path_table)
write.csv(top_table, file =path_table)

DF_top_table <-top_table[top_table$adj.P.Val < 0.1, ]

path_results <- paste0("results/LIMMA/model_1_LIMMA_results_olink_with_HC_filt.csv")

write.table(DF_top_table, file = path_results)

path_results <- paste0("results/LIMMA/model_1_LIMMA_results_olink_with_HC_filt.xlsx")

write.xlsx(DF_top_table, file = path_results)

table(DF_top_table$Comp)
```

```{r}
pca_data <- pca_data[!is.na(pca_data$H2_56),]
pca_data <- pca_data[!is.na(pca_data$status_smoking),]

group <- as.factor(pca_data$cluster)
fish <- pca_data$H2_52c
meat <- pca_data$H2_53a
fruit <- as.factor(pca_data$H2_56)
ethn <- pca_data$Ethnic
ethn[is.na(ethn)] <- 0
ethn <- as.factor(ethn)

pca_data$status_smoking <- as.vector(pca_data$status_smoking)
pca_data$status_smoking[pca_data$status_smoking == "Current smoker"] <- 2
pca_data$status_smoking[pca_data$status_smoking == "Ex smoker"] <- 1
pca_data$status_smoking[pca_data$status_smoking == "Never smoker"] <- 0
smok <- as.factor(pca_data$status_smoking)

design <- model.matrix( ~ 0 + group + smok + fruit + ethn)
```

```{r}
fit <- lmFit(t(pca_data[,-c(1:165)]), design)
```

```{r}
list_comp <- c(paste0("group",2:1))
list_pair <- data.frame(t(combn(list_comp,2)))
list_pair$comp <- paste0(list_pair$X1, "-", list_pair$X2)
comp <- list_pair$comp
names(comp) <- gsub("roup", "", comp)
```

```{r}
cont.matrix <- makeContrasts(G2_G1 = comp[1],
                             levels=design)

fit.cont <- contrasts.fit(fit, cont.matrix)
fit.cont <- eBayes(fit.cont)
```

```{r}
top_table <- data.frame(BIOCHEMICAL = NA, logFC= NA, P.Value= NA, adj.P.Val= NA, Comp= NA)

for (i in 1:length(comp)) {
  top_table_1 <- topTable(fit.cont, coef=i, adjust="BH", n = Inf, sort.by = "P")
  top_table_1$Comp <- comp[i]
  top_table_1$BIOCHEMICAL <- rownames(top_table_1)
  top_table_1 <- top_table_1[,c(8, 1, 4, 5, 7)]
  write.table(top_table_1$BIOCHEMICAL[top_table_1$adj.P.Val < 0.1], paste0("processing/MSEA/model_3_olink_", comp[i],".txt"), quote = FALSE, row.names = F)
  top_table <- rbind(top_table, top_table_1)
}

top_table <- top_table[complete.cases(top_table),]
path_table <- paste0("results/LIMMA/model_3_LIMMA_results_olink_with_HC.csv")

print(path_table)
write.csv(top_table, file =path_table)

DF_top_table <-top_table[top_table$adj.P.Val < 0.1, ]

path_results <- paste0("results/LIMMA/model_3_LIMMA_results_olink_with_HC_filt.csv")

write.table(DF_top_table, file = path_results)

path_results <- paste0("results/LIMMA/model_3_LIMMA_results_olink_with_HC_filt.xlsx")

write.xlsx(DF_top_table, file = path_results)

table(DF_top_table$Comp)
```
```{r}
length(DF_top_table$logFC[DF_top_table$logFC < 0])
```
```{r}
dge <- read.csv("results/LIMMA/model_3_LIMMA_results_olink_with_HC.csv")
names(dge)[2] <- "Gene_name"
```

```{r}
top_table <- dge
```


```{r}
sperm <- read.csv("manuscript/proteins_spermine_list.csv")
x <- as.vector(dge$Gene_name[dge$Gene_name %in% sperm$name_2 & !is.na(dge$Gene_name)])
sperm_2 <- top_table[top_table$Gene_name %in% sperm$name_2 & !is.na(top_table$Gene_name),]
write.csv(sperm_2, "manuscript/proteins_spermine_pathways_detected_olink_patients.csv")
```

```{r}
pca_data <- pca_data[,colnames(pca_data) %in% c("cluster", sperm_2$Gene_name, x)]
```

```{r}
pca_data$cluster <- ifelse(pca_data$cluster == 1, "HC-like", "At-risk")
```

```{r}
col <- c("#878782",	"#761212")
```

```{r}
my_comparisons <- list( c("HC-like", "At-risk"))
```

```{r}
pca_data$cluster <- factor(pca_data$cluster, levels = c("HC-like", "At-risk"))
```

## boxplots spermine/spermdine enzymes
```{r}
list_x <- list()
x = 1

for (i in 2:ncol(pca_data)) {
  table_1 <- pca_data[,c(i, 1)]
  a <- ggplot(table_1, aes(x = cluster, y = table_1[,1], fill = cluster)) + 
    geom_boxplot(position=position_dodge(1), size = 0.1, alpha =0.8, outlier.shape = NA)+ 
    labs(x="Cluster", y = colnames(pca_data)[i])+ 
    theme(axis.title.x = element_blank(),
          axis.title.y = element_text(size=16, face = "bold",color="black"),
          axis.text = element_text(color="black",size=16, face = "bold"),
          axis.text.x =element_text(color="black",size=16, face = "bold"),
          panel.border = element_blank(),
          axis.ticks.x = element_blank(),
          strip.text.x = element_text(size = 9,color="black"),
          legend.position="none",
          panel.background = element_rect(fill = "white", colour = "white", size = 0.5, linetype = "solid"),
          panel.grid.major = element_line(size = 0.5, linetype ='solid', colour = "grey"),
          panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "grey"),
          plot.title = element_text(hjust = 0.5, size = 20, face = "bold", vjust=2),
          legend.background=element_rect(fill = alpha("white", 0))) + 
    geom_jitter(shape=16, size=1, color="black", position=position_jitter(0.05))+ scale_fill_manual(values=col)+ 
  stat_compare_means(comparisons = my_comparisons)
  a
  ggsave(paste0("results/figures/boxplots/enzymes_spermidine_", colnames(pca_data)[i], "_proteomcis.pdf"), height = 4, width = 3)
  print(i)
  list_x[[x]] <- a
  x <- x + 1
}
```




```{r}
library(ggrepel)
```


```{r}
tt <- dge
tt$X <- NULL
name_ana <- unique(tt$Comp)
tt$color <- NA

for (i in 1:nrow(tt)){
  if(tt[i, 2] > 0 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "up_regulated"
  }
  if(tt[i, 2] < 0 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "down_regulated"
  }
  if(tt[i, 4] > 0.05){
    tt[i, ncol(tt)] <- "NS"
    #tt[i, 1] <- NA
  }
}

tt$BIOCHEMICAL <- ifelse(abs(tt$logFC) > 2 & tt$adj.P.Val < 0.0000001, as.vector(tt$Gene_name), NA)
length(tt$BIOCHEMICAL[!is.na(tt$BIOCHEMICAL)])

tt$color[is.na(tt$color)] <- "significant"
#tt$Gene_name[tt$color == "significant"] <- NA
cols <- c("up_regulated" = "#f1c232", "down_regulated" = "#86b7e8", "NS" = "grey", "significant" = "#586c6e")

vol <- ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val), colour = color, size = abs(logFC)))+ 
  geom_point(alpha = 1, na.rm = T)+ 
  theme(legend.title=element_text(size=2),legend.text=element_text(size=2),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=25),axis.title.x=element_text(size=25),
        axis.text.y=element_text(size=25),axis.text.x=element_text(size=25)) +
  labs(x="Log2 Fold Change",y="-log10 (adj.P.Val)")+
  geom_text_repel(aes(label = BIOCHEMICAL),size=2,label.size = 0.1, color = "black", xlim = c(NA, Inf),
    # Do not repel from top or bottom edges.
    ylim = c(-Inf, Inf))+ theme_classic()+ 
  geom_hline(yintercept=-log10(0.05), linetype="dashed", color = "black")+scale_color_manual(values = cols)

print(vol)
path_fig <- paste0("results/figures/volcano_plots/", name_ana, "_volcano_plot.pdf")
ggsave(path_fig, width = 6, height = 3)
```

```{r}
length(tt$logFC[tt$logFC > 1.5 & tt$adj.P.Val < 0.05])
length(tt$logFC[tt$logFC > 1 & tt$logFC < 1.5 & tt$adj.P.Val < 0.05])
length(tt$logFC[tt$logFC > 0 &tt$logFC < 1 & tt$adj.P.Val < 0.05])
```

```{r}
tt <- dge
tt$X <- NULL
name_ana <- unique(tt$Comp)
tt$color <- NA

for (i in 1:nrow(tt)){
  if(tt[i, 2] > 1.5 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "up_regulated_>1.5"
  }
  if(tt[i, 2] > 1 & tt[i, 2] < 1.5 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "up_regulated_1>x>1.5"
  }
  if(tt[i, 2] > 0 & tt[i, 2] < 1 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "up_regulated_0>x>1"
  }
  if(tt[i, 2] < 0 & tt[i, 4] < 0.05){
    tt[i, ncol(tt)] <- "down_regulated"
  }
  if(tt[i, 4] > 0.05){
    tt[i, ncol(tt)] <- "NS"
    #tt[i, 1] <- NA
  }
}

tt$BIOCHEMICAL <- ifelse(abs(tt$logFC) > 2 & tt$adj.P.Val < 0.0000001, as.vector(tt$Gene_name), NA)
length(tt$BIOCHEMICAL[!is.na(tt$BIOCHEMICAL)])


tt$color[is.na(tt$color)] <- "significant"
#tt$Gene_name[tt$color == "significant"] <- NA
cols <- c("up_regulated_>1.5" = "#cb4818",
          "up_regulated_1>x>1.5" = "#d27f28", 
          "up_regulated_0>x>1" = "#f1c232", 
          "down_regulated" = "#86b7e8", 
          "NS" = "grey", 
          "significant" = "#586c6e")

vol <- ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val), colour = color, size = abs(logFC)))+ 
  geom_point(alpha = 1, na.rm = T)+ 
  theme(legend.title=element_text(size=2),legend.text=element_text(size=2),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=25),axis.title.x=element_text(size=25),
        axis.text.y=element_text(size=25),axis.text.x=element_text(size=25)) +
  labs(x="Log2 Fold Change",y="-log10 (adj.P.Val)")+
  geom_text_repel(aes(label = BIOCHEMICAL),size=2,label.size = 0.1, color = "black", xlim = c(NA, Inf),
    # Do not repel from top or bottom edges.
    ylim = c(-Inf, Inf))+ theme_classic()+ 
  geom_hline(yintercept=-log10(0.05), linetype="dashed", color = "black")+scale_color_manual(values = cols)

print(vol)
path_fig <- paste0("results/figures/volcano_plots/", name_ana, "_volcano_plot_3_colors.pdf")
ggsave(path_fig, width = 10, height = 6)
```

```{r}
dge <- read.csv("results/LIMMA/model_3_LIMMA_results_olink_with_HC.csv")
names(dge)[2] <- "Gene_name"
gset=loadGSC("data/GSEA/c2.cp.kegg.v7.5.1.symbols_1_3_5.gmt")
path <- gset[[1]]
gsea <- read.csv("results/GSEA_proteomics_KEGG_model_3_pathways_clean.csv")
table_path_tot <- data.frame(Name = NA, Gene_name = NA)
gsea$Name <- paste0("KEGG_", gsea$Name)
gsea <- gsea[!gsea$Name %in% c("KEGG_MELANOGENESIS", "KEGG_NEUROACTIVE_LIGAND_RECEPTOR_INTERACTION", "KEGG_AMYOTROPHIC_LATERAL_SCLEROSIS_ALS"),]
gsea <- gsea[gsea$pvalue < 0.05,]

for (i in 1:length(path)) {
  if(names(path[i]) %in% gsea$Name){
    table_path <- data.frame(Name = rep(names(path[i]),length(path[[i]])), Gene_name = path[[i]])
    table_path_tot <- rbind(table_path_tot, table_path)
  }
}

top_table <- merge(dge, table_path_tot, by = "Gene_name")
top_table <- top_table[!duplicated(top_table$Gene_name),]
```


```{r}
top_table <- top_table[order(top_table$Name),]
top_table$Gene_name <- factor(top_table$Gene_name, levels = top_table$Gene_name)
```

```{r}
unique(top_table$Name)
```

## manathan plot
```{r}
gsea$sign
```

```{r}
length(unique(top_table$Name))
```
```{r}
#' Save figure as PDF in results
#'
#' @param file 
#' @param name_ana name comparison
#' @param indice_Gene
#' @param indice_LogFC 
#' @param indice_FDR 
#' @param width width of the figure
pretty_volcano <- function(file, name_ana, indice_Gene, indice_LogFC, indice_FDR){
  tt <- file
  tt$color <- NA
  print(ncol(tt))
  for (i in 1:nrow(tt)){
    if(tt[i, indice_LogFC] > 1 & tt[i, indice_FDR] < 0.05){
      print(tt[i, indice_Gene])
      tt[i, ncol(tt)] <- "up_regulated"
    }
    if(tt[i, indice_LogFC] < -1 & tt[i, indice_FDR] < 0.05){
      print(tt[i, indice_Gene])
      tt[i, ncol(tt)] <- "down_regulated"
    }
    if(tt[i, indice_FDR] > 0.05){
      tt[i, ncol(tt)] <- "NS"
      tt[i, indice_Gene] <- NA
    }
  }
  tt$color[is.na(tt$color)] <- "significant"
  tt$Gene_name[tt$color == "significant"] <- NA
  cols <- c("up_regulated" = "#cc0000", "down_regulated" = "#1b3651", "NS" = "darkgrey", "significant" = "#ffff99")
  vol <- ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val), colour = logFC))+ 
  geom_point(size=2, alpha = 1, na.rm = T, aes(colour=logFC, fill=logFC), 
  shape = 21,size = 12,colour = "black")+
  scale_fill_gradientn(colours=c("#1b3651","#527190","white","#ff6666","#cc0000"),
                         values=rescale(c(min(tt$logFC),min(tt$logFC)/4, 0,max(tt$logFC)/4, max(tt$logFC))), 
                         space = "Lab")+ 
  theme(legend.title=element_text(size=2),legend.text=element_text(size=2),
        legend.key.size=unit(0.7,"line"),plot.title = element_text(hjust = 0.5),
        axis.title.y=element_text(size=25),axis.title.x=element_text(size=25),
        axis.text.y=element_text(size=25),axis.text.x=element_text(size=25)) +
  labs(x="Log2 Fold Change",y="-log10 (adj.P.Val)")+
  geom_text_repel(aes(label = Gene_name),size=2,label.size = 0.1, color = "black", xlim = c(NA, Inf),
    # Do not repel from top or bottom edges.
    ylim = c(-Inf, Inf))+ theme_classic()

  print(vol)
  path_fig <- paste0("results/figures/volcano_plots/", name_ana, "_volcano_plot.pdf")
  ggsave(path_fig, width = 4, height = 3)
  return(tt)

}
```



```{r}
library(ggrepel)
library(scales)
```

```{r}
names(dge)[2] <- "Gene_name"
```

```{r}
tt <- pretty_volcano(dge, "COCOMO_3_Layers_prot_limma_corrected_2", 2, 3, 5)
```
