---
title: "Statistics"
output: html_notebook
---


### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```


```{r}
library(summarize)
library(dplyr)
library(xlsx)
```

## load clinical data whole patients
```{r}
clinical_whole <- read.xlsx("data/whole_patients/CO_HIV_new.xlsx", 1)
names(clinical_whole)[1] <- "id"
characteristics <- read.xlsx("data/whole_patients/Characteristics.xlsx", 1)
clinical_whole <- merge(characteristics, clinical_whole, by = "id")
```

## load file for patients study
```{r}
clinical <- read.csv("processing/clinical_data_clean.csv", stringsAsFactors = FALSE)
colnames(clinical) <- gsub("\\.x", "", colnames(clinical))
m <- colnames(clinical)
clinical <- clinical[,c(2, 9, 40, 41, 42, 43)]
colnames(clinical)[1] <- "id"
```

## merge files
```{r}
clinical_whole <- merge(clinical_whole, clinical, by = "id")
```

```{r}
n <- c("H2_56", "H2_52c", "status_smoking")
```

## select items for table
```{r}
clinical_2 <- clinical_whole[, colnames(clinical_whole) %in% c("id","Duration.of.therapy","SAT", "VAT", "Combined_therapy","eGFR", "H2_53a","alder","sex", "METS", "CD4_ART", "bmi", "bmikat", m, n)]
```

```{r}
clinical_2$H2_52c <- as.numeric(as.vector(clinical_2$H2_52c))
```
```{r}
data$H2_56
```

```{r}
data <- clinical_2
data$H2_56 <- as.vector(data$H2_56)
data$H2_56[data$H2_56 == 0] <- 1
data$H2_56[data$H2_56 == 4] <- 2
data$H2_56[data$H2_56 == 3] <- 2
data$H2_56[data$H2_56 == 6] <- 5
data$H2_56[data$H2_56 == 7] <- 5
data$H2_56 <- as.factor(data$H2_56)
```

## change categories
```{r}
data$Combined_therapy <- gsub(".*ABC.*", "ABC", data$Combined_therapy)
data$Combined_therapy <- gsub(".*AZT.*", "Other", data$Combined_therapy)
data$Combined_therapy <- gsub(".*TAF.*", "TAF-TDF", data$Combined_therapy)
data$Combined_therapy <- gsub(".*TDF.*", "TAF-TDF", data$Combined_therapy)
data$Combined_therapy[data$cluster != "Ctrl"] <- gsub(".*\\/.*", "Other", data$Combined_therapy[data$cluster != "Ctrl"])
data$Combined_therapy <- factor(data$Combined_therapy, levels = c("ABC", "TAF-TDF", "Other"))
```

```{r}
table(data$Combined_therapy)
```

```{r}
x <- which(names(data) == "Combined_therapy")

names(data)[x] <- "first_drug"
data$first_drug
```

```{r}
clinical_2 <- data
```

```{r}
clinical_2$Ethnic <- as.factor(clinical_2$Ethnic)
clinical_2$Origin <- as.factor(clinical_2$Origin)
clinical_2$Transm_mode <- as.factor(clinical_2$Transm_mode)
clinical_2$sex <- as.factor(clinical_2$sex)
clinical_2$alcohol <- as.numeric(as.character(clinical_2$alcohol))

clinical_2$ob6 <- as.numeric(clinical_2$ob6)
clinical_2$ob10 <- as.numeric(clinical_2$ob10)
clinical_2$ob11 <- as.numeric(clinical_2$ob11)
```

```{r}
clinical_2$ART1_prev_dur <- as.numeric(clinical_2$ART1_prev_dur)
```

```{r}
clinical_2$Ethnic[clinical_2$Ethnic != 1] <- 2

clinical_2$Transm_mode[!clinical_2$Transm_mode %in% c(1,6) & !is.na(clinical_2$Transm_mode)] <- 2

```

```{r}
clinical_2$CD4_CD8 <- clinical_2$CD4/clinical_2$CD8
```

```{r}
clinical_2$log10VL_ART <- log10(clinical_2$VL_ART)
#clinical_2$VL_ART <- NULL
```

```{r}
table(clinical_2$Transm_mode)
```

## add drug previous exposure
```{r}
drug <- read.csv("data/clinical/cocomo_drug_comorbidities_data.csv")
drug$X <- NULL
drug$ddiAZTd4t <- ifelse(drug$ddiAZTd4t == TRUE, 1 , 0)
colnames(drug)[1] <- "id"
drug$alat <- as.numeric(drug$alat)
drug$creatini <- as.numeric(drug$creatini)
drug$ddiAZTd4t <- factor(drug$ddiAZTd4t)
```

```{r}
clinical_2 <- merge(clinical_2, drug, by = "id")
```

## load olink data
```{r}
data <- read.csv("processing/olink_data_new_ids.csv", row.names = 1)
```

```{r}
clinical_2$VL <- ifelse(clinical_2$VL < 50, "<50", ">50")
clinical_2$VL <- as.factor(clinical_2$VL)
```

```{r}
clinical_2 <- clinical_2[clinical_2$id %in% rownames(data),]
```

```{r}
clinical_2$X3rd_Drug <- factor(clinical_2$X3rd_Drug)
```

```{r}
# Function returning compact column classes
col_classes <- function(df) {
    t(as.data.frame(lapply(df, function(x) paste(class(x), collapse = ','))))
}
# Return example data's column classes
```

```{r}
write.csv(clinical_2, "processing/clinical_data_sub_cohort_data.csv")

clinical_2$id <- NULL

data_factor <- clinical_2[, c(which(col_classes(clinical_2) == "factor"))]
data_numeric <- clinical_2[, c(which(col_classes(clinical_2) != "factor"))]
```

## save data numeric
```{r}
table_numeric <- data.frame(parameter = names(data_numeric), Med_IQR = NA)
j = 1


for (i in 1:ncol(data_numeric)){
  c1 <- data_numeric[,i]
  x <- paste0(round(medIQR(c1)[[1]], 2), "(", round(medIQR(c1)[[2]], 2), "-", round(medIQR(c1)[[3]], 2), ")")
  table_numeric[c(j), 2] <- x
  j = j + 1
}

write.xlsx(table_numeric, "results/clinical/sub_cohort_numeric_values.xlsx")
```

```{r}
data_factor <- data.frame(cluster = 1, data_factor)
```

## save data factor
```{r}
table_factor <- data.frame(Var1 = NA, Var2 = NA, Level = NA, Freq= NA, Freq2 = NA, Parameter = NA)
j = 1

for (i in 2:ncol(data_factor)) {
  x <- data.frame(t(table(data_factor$cluster, data_factor[,i])))
  x$Level <- x$Var1
  x$Var1 <- paste0(names(data_factor)[i], "_", x$Var1, "_", x$Var2)
  x$Freq2 <- ""
  x$Freq2[x$Var2 == 1] <- paste0(x$Freq[x$Var2 == 1], "(", round(x$Freq[x$Var2 == 1]/sum(x$Freq[x$Var2 == 1])*100, 2), "%)")
  x$Parameter <- names(data_factor)[i]
  table_factor <- rbind(x,table_factor)
}

table_factor$Var1 <- gsub("_1$", "", table_factor$Var1)

table_factor <- table_factor[,colnames(table_factor) %in% c("Var2", "Parameter", "Level", "Freq2")]
names(table_factor)[1] <- "cluster"
table_factor$cluster <- NULL
write.xlsx(table_factor, "results/clinical/sub_cohort_factor_values.xlsx")
```
