---
title: "Pathways community 3"
output: html_notebook
---




### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```


```{r}
table_summary <- read.csv("results/networks/Results_centrality_networks_CPMCo_expression_3_layers.csv")
```

```{r}
table_GSEA <- data.frame(Term = NA, Overlap = NA, Adjusted.P.value = NA, Genes = NA, Group = NA)

x <- list.files("results/co_expression")
x <- x[-c(12:14)]
y <- 1

for (i in x) {
  c <- read.delim(paste0("results/co_expression", "/", i))
  c <- c[,c(2, 3, 5, 7)]
  c <- c[complete.cases(c),]
  c$Group <- rep(y, nrow(c))
  table_GSEA <- rbind(table_GSEA, c)
  y = y + 1
}
```

```{r}
table_nodes <- read.csv("results/networks/Table_nodes_CPMCo_expression_3_layers.csv")
table_nodes <- table_nodes[table_nodes$Community == 3, ]
table(table_nodes$type_1)
```

```{r}
write.table(table_nodes$feat1[table_nodes$type_1 == "met"], "processing/com_3_metabolites.txt", quote = FALSE, row.names = FALSE)
```

```{r}
name_ana <- "co_expression_C3_proteomics_sigdb"
```

```{r}
gset=loadGSC("data/GSEA/h.all.v7.5.1.symbols.gmt")
```


```{r}
c1 <- read.csv("results/LIMMA/model_1_LIMMA_results_olink_with_HC.csv")
c1 <- c1[c1$BIOCHEMICAL %in% table_nodes$feat1, ]
c1_1 <- c1[c1$Comp == "group2-group1",]
c1_2 <- c1[c1$Comp == "group1-groupCtrl",]
c1_3 <- c1[c1$Comp == "group2-groupCtrl",]

c2 <- read.csv("results/LIMMA/model_2_LIMMA_results_olink_with_HC.csv")
c2 <- c2[c2$BIOCHEMICAL %in% table_nodes$feat1, ]
c3 <- read.csv("results/LIMMA/model_3_LIMMA_results_olink_with_HC.csv")
c3 <- c3[c3$BIOCHEMICAL %in% table_nodes$feat1, ]

data_sets <- list(c1_1, c1_2, c1_3, c2, c3)
names_data <- c("model_1_C2C1", "model_1_C1CT", "model_1_C2CT", "model_2", "model_3")
```

## load GSEA

```{r}
table_global <- data.frame(Name = NA, Stat..dist.dir.up.= NA, p.adj..dist.dir.up.= NA, Genes..up. = NA, Stat..dist.dir.dn.= NA, p.adj..dist.dir.dn.= NA, Genes..down. = NA, comp = NA, sign = NA)

for (i in 1:length(data_sets)) {
  tryCatch({
    DESeqout <- data_sets[[i]]
    pval= as.matrix(DESeqout[ ,5]) 
    fc= as.matrix(DESeqout[ ,3]) 

    row.names(pval)=DESeqout[ ,1]
    row.names(fc)=DESeqout[ ,1]
  
    #Main function in PIANO. Uses the pvalues, fold-changes, and gene sets. 
    gsaRes <- runGSA(pval,fc,gsc=gset, nPerm = 1000, adjMethod = "fdr", gsSizeLim=c(10,800))
    #Writes the output from PIANO to a file "piano.txt". Setting "save=FALSE" simply shows the result from PIANO
    GSAsummaryTable(gsaRes, save=TRUE, file=paste0("results/GSEA_KEGG/", name_ana, "_",names_data[i], "_2.txt"))
    c <- read.delim(paste0("results/GSEA_KEGG/", name_ana, "_", names_data[i], "_2.txt"))
    c <- c[,c(1, 3, 5, 12, 6, 8, 16)]
    #c <- select(c, Name, Stat..dist.dir.up., p.adj..dist.dir.up., Genes..up., Stat..dist.dir.dn., p.adj..dist.dir.dn., Genes..down.)
    c_up <- c[c$p.adj..dist.dir.up. < 0.2, ]
    c_down <- c[c$p.adj..dist.dir.dn. < 0.2, ]
    print(nrow(c_up))
    print(nrow(c_down))
    
    table_piano <- data.frame(Name = NA, Stat..dist.dir.up.= NA, p.adj..dist.dir.up.= NA, Genes..up. = NA, Stat..dist.dir.dn.= NA, p.adj..dist.dir.dn.= NA, Genes..down. = NA, comp = NA, sign = NA)
    if (nrow(c_up) > 1) {
      c_up$comp <- names_data[i]
      c_up$sign <- "up"
      table_piano <- rbind(c_up, table_piano)
    }
    if (nrow(c_down) > 1) {
      c_down$comp <- names_data[i]
      c_down$sign <- "down"
      table_piano <- rbind(c_down, table_piano)
    }
    
    table_global <- rbind(table_global, table_piano)
    
  }, error=function(e){cat("ERROR :",i, "\n")})
}
```

```{r}
table_global_2 <- table_global[!is.na(table_global$Name),]
write.csv(table_global_2, paste0("results/", name_ana, "_all_comparisons.csv"))
```

```{r}
table_global_2 <- read.csv(paste0("results/", name_ana, "_all_comparisons.csv"))
```

```{r}
table_bubble <- table_global_2[,c(2, 4, 5, 9, 10)]
table_bubble <- table_bubble[table_bubble$comp == "model_3",]
write.csv(table_bubble, "results/pathways_C3_co-expression_proteomics.csv")
```

## bubble plot
```{r}
a <- ggplot(table_bubble, aes(y=Name,  x= 1, size = Genes..up., color = sign, label = Name))+geom_point()+theme_light()+ labs(title="", x="", y="", fill="")+ theme(axis.text.x = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
a

ggsave(paste0("results/figures/", name_ana, "_bubble_plot_model_3_proteins.pdf"), height = 4, width = 6)
```

```{r}
x <- read.delim("results/MSEA/CUSTOM140613145548480.human.enrichr.reports.txt")
x <- x[x$Adjusted.P.value < 0.2,]
write.csv(x, "results/pathways_C3_co-expression_metabolomics.csv")
```

```{r}
x$Overlap <- as.numeric(gsub("/.*", "", x$Overlap))
```

```{r}
a <- ggplot(x, aes(y=Term,  x= 1, size = Overlap))+geom_point()+theme_light()+ labs(title="", x="", y="", fill="")+ theme(axis.text.x = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank())
a

ggsave(paste0("results/figures/", name_ana, "_bubble_plot_model_3_metabolites.pdf"), height = 4, width = 6)
```

