---
title: "Pathways "
output: html_notebook
---


### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("~/Desktop/Code-PHD/COCOMO_txn/")) 
```

```{r}
library(piano)
```

```{r}
gset=loadGSC("data/GSEA/c2.cp.kegg.v7.5.1.symbols_1_3_5.gmt")
```

```{r}
data <- read.csv("processing/table_edges_BNN_proteomics.csv")
genes <- unique(c(as.vector(data$from), as.vector(data$to)))
write.csv(genes, "processing/top_genes_proteomics.csv")

c2 <- read.csv("results/LIMMA/model_2_LIMMA_results_olink_with_HC.csv")
DESeqout <- c2[c2$BIOCHEMICAL %in% genes,]
```

```{r}
pval= as.matrix(DESeqout[ ,5]) 
fc= as.matrix(DESeqout[ ,3]) 

row.names(pval)=DESeqout[ ,1]
row.names(fc)=DESeqout[ ,1]
```

```{r}
name_ana <- "top_prot_RF"
```

```{r}
gsaRes <- runGSA(pval,fc, gsc=gset, nPerm = 1000, adjMethod = "fdr", gsSizeLim=c(1, 187))
#Writes the output from PIANO to a file "piano.txt". Setting "save=FALSE" simply shows the result from PIANO
GSAsummaryTable(gsaRes, save=TRUE, file=paste0("results/GSEA_KEGG/", name_ana, "_2.txt"))
c <- read.delim(paste0("results/GSEA_KEGG/", name_ana, "_2.txt"))
c <- c[,c(1, 3, 5, 12, 6, 8, 16)]
#c <- select(c, Name, Stat..dist.dir.up., p.adj..dist.dir.up., Genes..up., Stat..dist.dir.dn., p.adj..dist.dir.dn., Genes..down.)
c_up <- c[c$p.adj..dist.dir.up. < 0.2, ]
c_down <- c[c$p.adj..dist.dir.dn. < 0.2, ]
print(nrow(c_up))
print(nrow(c_down))
    
table_piano <- data.frame(Name = NA, Stat..dist.dir.up.= NA, p.adj..dist.dir.up.= NA, Genes..up. = NA, Stat..dist.dir.dn.= NA, p.adj..dist.dir.dn.= NA, Genes..down. = NA, comp = NA, sign = NA)
if (nrow(c_up) > 1) {
  c_up$comp <- names_data[i]
  c_up$sign <- "up"
  table_piano <- rbind(c_up, table_piano)
}
if (nrow(c_down) > 1) {
  c_down$comp <- names_data[i]
  c_down$sign <- "down"
  table_piano <- rbind(c_down, table_piano)
}

```

